### ISSUE TITLE
Cuda 

### ISSUE THREAD

**Issue by SolarisNeko** [cmdr2/stable-diffusion-ui#1027]
**Describe the bug**
I try to train in SD-WebUI，but it alwasy tell me ’CUBLAS_STATUS_ALLOC_FAILED ‘
I have try multi device

**To Reproduce**
1. Go to 'Train Tab'
2. Click on 'Max Step -> 1500'
3. Click on 'Train Embedding'

**Expected behavior**
I want to train can run.

**Screenshots**

**Desktop (please complete the following information):**
- Version: Stable-Diffusion-1.5
- OS: Window 11
- Browser: Chrome
- GPU: Nvidia 2080 / Nvidia 3090

**Additional context**

# Bug Log
Training at rate of 0.005 until step 1500
Preparing dataset...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.53it/s] 
  0%|                                                                                                                                                                                         | 0/1500 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:\App_Code\AI_Draw_Image\stable-diffusion-webui-master\modules\textual_inversion\textual_inversion.py", line 503, in train_embedding
    scaler.scale(loss).backward()
  File "D:\App_Code\AI_Draw_Image\stable-diffusion-webui-master\venv\lib\site-packages\torch\_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "D:\App_Code\AI_Draw_Image\stable-diffusion-webui-master\venv\lib\site-packages\torch\autograd\__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "D:\App_Code\AI_Draw_Image\stable-diffusion-webui-master\venv\lib\site-packages\torch\autograd\function.py", line 267, in apply
    return user_fn(self, *args)
  File "D:\App_Code\AI_Draw_Image\stable-diffusion-webui-master\venv\lib\site-packages\torch\utils\checkpoint.py", line 141, in backward
    outputs = ctx.run_function(*detached_inputs)
  File "D:\App_Code\AI_Draw_Image\stable-diffusion-webui-master\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 262, in _forward
    x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x
  File "D:\App_Code\AI_Draw_Image\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\App_Code\AI_Draw_Image\stable-diffusion-webui-master\modules\hypernetworks\hypernetwork.py", line 400, in attention_CrossAttention_forward
    q = self.to_q(x)
  File "D:\App_Code\AI_Draw_Image\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\App_Code\AI_Draw_Image\stable-diffusion-webui-master\extensions-builtin\Lora\lora.py", line 178, in lora_Linear_forward
    return lora_forward(self, input, torch.nn.Linear_forward_before_lora(self, input))
  File "D:\App_Code\AI_Draw_Image\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

**Comment by cmdr2** [comment]
Hi, but you're using a different project (automatic1111). Please contact them for support: https://github.com/AUTOMATIC1111/stable-diffusion-webui
