### ISSUE TITLE
ModuleNotFoundError: No module named 'splitAttention'

### ISSUE THREAD

**Issue by ddaydd** [cmdr2/stable-diffusion-ui#113]
Hello, I have this error when I start. 

```
File "c:\stable-diffusion-ui\stable-diffusion\optimizedSD\openaimodelSplit.py", line 16, in <module>
    from splitAttention import SpatialTransformer
ModuleNotFoundError: No module named 'splitAttention'
```

windows 11

**Comment by bbfrederick** [comment]
Same here (Windows 10).

**Comment by casc1701** [comment]
Windows 11 here. Same problem, Between two images, it stopped working asking for SplitAttention module.

**Comment by danielbisar** [comment]
Same error on startup:

Traceback (most recent call last):
  File "E:\stable-diffusion-ui\ui\server.py", line 64, in ping
    runtime.load_model(ckpt_to_use="sd-v1-4.ckpt")
  File "E:\stable-diffusion-ui\ui\sd_internal\runtime.py", line 84, in load_model
    model = instantiate_from_config(config.modelUNet)
  File "e:\stable-diffusion-ui\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "e:\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 362, in __init__
    self.model1 = DiffusionWrapper(self.unetConfigEncode)
  File "e:\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 309, in __init__
    self.diffusion_model = instantiate_from_config(diff_model_config)
  File "e:\stable-diffusion-ui\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "e:\stable-diffusion-ui\stable-diffusion\ldm\util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "E:\stable-diffusion-ui\stable-diffusion\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "e:\stable-diffusion-ui\stable-diffusion\optimizedSD\openaimodelSplit.py", line 16, in <module>
    from splitAttention import SpatialTransformer
ModuleNotFoundError: No module named 'splitAttention'

**Comment by Ariewcdoa** [comment]
Same issue here. Suddenly lagged my system between renders and had to restart. After that I got this error.

**Comment by ddaydd** [comment]
fixed, thanks

**Comment by cmdr2** [comment]
Thanks! Yes, the issue was with a dependency which had an error. I've updated our project to stop pulling from their main branch, and instead use tested versions of their package.
