### ISSUE TITLE
Module splitAttention not found

### ISSUE THREAD

**Issue by wxyEquation** [cmdr2/stable-diffusion-ui#114]
Here is the traceback:

Traceback (most recent call last):
  File "C:\stable-diffusion-ui\ui\server.py", line 68, in ping
    runtime.load_model_ckpt(ckpt_to_use="sd-v1-4")
  File "C:\stable-diffusion-ui\ui\sd_internal\runtime.py", line 100, in load_model_ckpt
    model = instantiate_from_config(config.modelUNet)
  File "c:\stable-diffusion-ui\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "c:\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 362, in __init__
    self.model1 = DiffusionWrapper(self.unetConfigEncode)
  File "c:\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 309, in __init__
    self.diffusion_model = instantiate_from_config(diff_model_config)
  File "c:\stable-diffusion-ui\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "c:\stable-diffusion-ui\stable-diffusion\ldm\util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "C:\stable-diffusion-ui\stable-diffusion\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\stable-diffusion-ui\stable-diffusion\optimizedSD\openaimodelSplit.py", line 16, in <module>
    from splitAttention import SpatialTransformer
ModuleNotFoundError: No module named 'splitAttention'

**Comment by SpockThePainter** [comment]
I'm getting the same error. It looks like everyone is having trouble, so at least its not our fault. lol

**Comment by ddaydd** [comment]
it was fixed, try again :)

**Comment by jjtolton** [comment]
See https://github.com/cmdr2/stable-diffusion-ui/pull/117/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R27 ... it's a circular import error.  Short term workaround if working in bleeding is to `./stable-diffusion/env/bin/pip install -e ./stable-diffusion`.  This will "allow" circular imports, and the `-e` flag means it will be live so you don't have to reinstall between runs.  

Not sure if it's cleaner to fix this by adding the `pip install -e ./stable-diffusion` into the startup script or if moving the imports around to avoid the circ dependency is a better approach.  I'm happy to make the PR with some direction from maintainers, just not sure what their preferred style is.

**Comment by cmdr2** [comment]
Resolved in https://github.com/cmdr2/stable-diffusion-ui/issues/113 . Was an issue with a downstream dependency. Thanks
