### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'astype'

### ISSUE THREAD

**Issue by van1027** [cmdr2/stable-diffusion-ui#1180]
**Describe the bug**
Test diffusers mode stopped working.

06:32:46.634 ERROR cuda:0 Traceback (most recent call last):                                                                                                                                                            task_manager.py:346
  File "C:\stable-diffusion-ui\ui\easydiffusion\task_manager.py", line 336, in thread_render
    task.response = renderer.make_images(
  File "C:\stable-diffusion-ui\ui\easydiffusion\renderer.py", line 51, in make_images
    images, seeds = make_images_internal(req, task_data, data_queue, task_temp_images, step_callback)
  File "C:\stable-diffusion-ui\ui\easydiffusion\renderer.py", line 71, in make_images_internal
    images, user_stopped = generate_images_internal(
  File "C:\stable-diffusion-ui\ui\easydiffusion\renderer.py", line 118, in generate_images_internal
    images = generate_images(context, callback=callback, **req.dict())
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\sdkit\generate\image_generator.py", line 61, in generate_images
    return make_with_diffusers(
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\sdkit\generate\image_generator.py", line 278, in make_with_diffusers
    return operation_to_apply(**cmd).images
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion_img2img.py", line 731, in __call__
    callback(i, t, latents)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\sdkit\generate\image_generator.py", line 244, in <lambda>
    cmd["callback"] = lambda i, t, x_samples: callback(x_samples, i, operation_to_apply) if callback else None
  File "C:\stable-diffusion-ui\ui\easydiffusion\renderer.py", line 211, in on_image_step
    progress["output"] = update_temp_img(context.partial_x_samples, task_temp_images)
  File "C:\stable-diffusion-ui\ui\easydiffusion\renderer.py", line 181, in update_temp_img
    images = diffusers_latent_samples_to_images(context, x_samples)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\sdkit\utils\latent_utils.py", line 98, in diffusers_latent_samples_to_images
    return model.numpy_to_pil(samples)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1362, in numpy_to_pil
    images = (images * 255).round().astype("uint8")
AttributeError: 'Tensor' object has no attribute 'astype'

06:32:47.806 INFO cuda:0 Session 1681997526072 task 1715443652160 failed!

**To Reproduce**
generate image 2 image with LoRA

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by JeLuF** [comment]
Please restart Easy Diffusion to update to the newest sdkit version. This should fix the issue.

**Comment by cmdr2** [comment]
Hi @van1027 This has been fixed in the latest version of beta, please restart the program. Thanks!
