### ISSUE TITLE
ModuleNotFoundError: No module named 'entrypoints'

### ISSUE THREAD

**Issue by vladbph** [cmdr2/stable-diffusion-ui#1193]
Ubuntu 20.04, Latest updates caused this error not seen before:

```

./start.sh 
/usr/bin/curl
/bin/tar
/bin/bzip2
/usr/bin/git
git version 2.25.1
/home/vladbph/ed/easy-diffusion/installer_files/env/bin/conda
conda 23.3.1


Easy Diffusion

Easy Diffusion's git repository was already installed. Updating from main..
HEAD is now at ce95072 Update README.md
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
torch: 2.0.0
torchvision: 0.15.1
sdkit: 1.0.80
stable-diffusion-sdkit: 2.1.4
rich: 12.6.0
uvicorn: 0.19.0
fastapi: 0.85.1
Traceback (most recent call last):
  File "../scripts/check_models.py", line 3, in <module>
    from sdkit.models import download_model, get_model_info_from_db
  File "/home/vladbph/ed/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/models/__init__.py", line 1, in <module>
    from .model_downloader import (
  File "/home/vladbph/ed/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/models/model_downloader.py", line 4, in <module>
    from sdkit.utils import download_file, log
  File "/home/vladbph/ed/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/utils/__init__.py", line 20, in <module>
    from .latent_utils import (
  File "/home/vladbph/ed/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/utils/latent_utils.py", line 9, in <module>
    from diffusers import StableDiffusionImg2ImgPipeline
  File "/home/vladbph/ed/easy-diffusion/installer_files/env/lib/python3.8/site-packages/diffusers/__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "/home/vladbph/ed/easy-diffusion/installer_files/env/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 34, in <module>
    from .utils import (
  File "/home/vladbph/ed/easy-diffusion/installer_files/env/lib/python3.8/site-packages/diffusers/utils/__init__.py", line 21, in <module>
    from .accelerate_utils import apply_forward_hook
  File "/home/vladbph/ed/easy-diffusion/installer_files/env/lib/python3.8/site-packages/diffusers/utils/accelerate_utils.py", line 24, in <module>
    import accelerate
  File "/home/vladbph/ed/easy-diffusion/installer_files/env/lib/python3.8/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/vladbph/ed/easy-diffusion/installer_files/env/lib/python3.8/site-packages/accelerate/accelerator.py", line 37, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "/home/vladbph/ed/easy-diffusion/installer_files/env/lib/python3.8/site-packages/accelerate/tracking.py", line 64, in <module>
    import mlflow
  File "/home/vladbph/.local/lib/python3.8/site-packages/mlflow/__init__.py", line 41, in <module>
    from mlflow import projects  # pylint: disable=unused-import
  File "/home/vladbph/.local/lib/python3.8/site-packages/mlflow/projects/__init__.py", line 9, in <module>
    import mlflow.projects.databricks
  File "/home/vladbph/.local/lib/python3.8/site-packages/mlflow/projects/databricks.py", line 12, in <module>
    from mlflow import tracking
  File "/home/vladbph/.local/lib/python3.8/site-packages/mlflow/tracking/__init__.py", line 8, in <module>
    from mlflow.tracking.client import MlflowClient
  File "/home/vladbph/.local/lib/python3.8/site-packages/mlflow/tracking/client.py", line 27, in <module>
    from mlflow.tracking._model_registry.client import ModelRegistryClient
  File "/home/vladbph/.local/lib/python3.8/site-packages/mlflow/tracking/_model_registry/client.py", line 18, in <module>
    from mlflow.tracking._model_registry import utils, DEFAULT_AWAIT_MAX_SLEEP_SECONDS
  File "/home/vladbph/.local/lib/python3.8/site-packages/mlflow/tracking/_model_registry/utils.py", line 9, in <module>
    from mlflow.tracking._model_registry.registry import ModelRegistryStoreRegistry
  File "/home/vladbph/.local/lib/python3.8/site-packages/mlflow/tracking/_model_registry/registry.py", line 4, in <module>
    from mlflow.tracking.registry import StoreRegistry
  File "/home/vladbph/.local/lib/python3.8/site-packages/mlflow/tracking/registry.py", line 2, in <module>
    import entrypoints
ModuleNotFoundError: No module named 'entrypoints'
Press any key to continue

```

**Comment by provVladBurlik** [comment]
removing mlflow fixed the issue
