### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by yyheart** [cmdr2/stable-diffusion-ui#1262]
fastapi: 0.92.0
No module 'xformers'. Proceeding without it.
stable-diffusion model(s) found.
gfpgan model(s) found.
Traceback (most recent call last):
  File "..\scripts\check_models.py", line 57, in init
    download_if_necessary(model_type, model["file_name"], model["model_id"])
  File "..\scripts\check_models.py", line 44, in download_if_necessary
    known_model_is_corrupt = known_model_exists and hash_file_quick(model_path) != expected_hash
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\hash_utils.py", line 41, in hash_file_quick
    return compute_quick_hash(
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\hash_utils.py", line 60, in compute_quick_hash
    end_bytes = read_bytes_fn(offset=total_size - 0x100000, count=0x10000)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\hash_utils.py", line 36, in read_bytes
    f.seek(offset)
OSError: [Errno 22] Invalid argument
Error downloading the realesrgan model. Sorry about that, please try to:
1. Run this installer again.
2. If that doesn't fix it, please try to download the file manually. The address to download from, and the destination to save to are printed above this message.
3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB
4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues
Thanks!

**Comment by cmdr2** [comment]
Please delete the `models\gfpgan` folder and run `Start Stable Diffusion UI.cmd` again. It'll repair itself. Thanks!
