### ISSUE TITLE
i used "pip install xformors" to successfully install xformer but it seems that it doesn't work, i guess i need to set it up in inviroment?

### ISSUE THREAD

**Issue by ZZjm666** [cmdr2/stable-diffusion-ui#1294]
No module 'xformers'. Proceeding without it.
stable-diffusion model(s) found.
gfpgan model(s) found.
realesrgan model(s) found.
Traceback (most recent call last):
  File "..\scripts\check_models.py", line 57, in init
    download_if_necessary(model_type, model["file_name"], model["model_id"])
  File "..\scripts\check_models.py", line 40, in download_if_necessary
    expected_hash = get_model_info_from_db(model_type=model_type, model_id=model_id)["quick_hash"]
TypeError: 'NoneType' object is not subscriptable
Error downloading the vae model. Sorry about that, please try to:
1. Run this installer again.
2. If that doesn't fix it, please try to download the file manually. The address to download from, and the destination to save to are printed above this message.
3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB

**Comment by JeLuF** [comment]
The error message suggests that your sdkit version is out of date. Can you please share the full log?

**Comment by AiPacino9** [comment]
i solved my problem after I manually set the environment variable value named "COMMANDLINE_ARGS" to "--formers".

**Comment by JeLuF** [comment]
> i solved my problem after I manually set the environment variable value named "COMMANDLINE_ARGS" to "--formers".

This environment variable has no meaning in EasyDiffusion. It's a setting for a different software.
