### ISSUE TITLE
After installation, it says starting server, then it stops

### ISSUE THREAD

**Issue by Esfekia** [cmdr2/stable-diffusion-ui#133]
"Stable Diffusion UI - v2"

"Stable Diffusion UI's git repository was already installed. Updating from main.."
HEAD is now at c283d31 Don't cache the index page
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
sd-ui-files\ui\index.html
sd-ui-files\ui\modifiers.json
sd-ui-files\ui\server.py
sd-ui-files\ui\media\ding.mp3
sd-ui-files\ui\media\kofi.png
sd-ui-files\ui\sd_internal\runtime.py
sd-ui-files\ui\sd_internal\__init__.py
7 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
"Stable Diffusion's git repository was already installed. Updating.."
HEAD is now at d154155 Merge pull request #122 from ryudrigo/main
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

HEAD is now at d154155 Merge pull request #122 from ryudrigo/main
"Packages necessary for Stable Diffusion were already installed"
"Packages necessary for Stable Diffusion UI were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded"

"Stable Diffusion is ready!"

started in  C:\Users\serta\Documents\stable-diffusion-ui\stable-diffusion
←[32mINFO←[0m:     Started server process [←[36m3720←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://0.0.0.0:9000←[0m (Press CTRL+C to quit)
←[32mINFO←[0m:     127.0.0.1:59984 - "←[1mGET / HTTP/1.1←[0m" ←[32m200 OK←[0m
Loading model from sd-v1-4.ckpt
Global Step: 470000
UNet: Running in eps-prediction mode
CondStage: Running in eps-prediction mode
Traceback (most recent call last):
  File "C:\Users\serta\Documents\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\configuration_utils.py", line 650, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "C:\Users\serta\Documents\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\configuration_utils.py", line 734, in _dict_from_json_file
    return json.loads(text)
  File "C:\Users\serta\Documents\stable-diffusion-ui\stable-diffusion\env\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\serta\Documents\stable-diffusion-ui\stable-diffusion\env\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\serta\Documents\stable-diffusion-ui\stable-diffusion\env\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 88 column 3 (char 2317)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\serta\Documents\stable-diffusion-ui\ui\server.py", line 71, in ping
    runtime.load_model(ckpt_to_use="sd-v1-4.ckpt")
  File "C:\Users\serta\Documents\stable-diffusion-ui\ui\sd_internal\runtime.py", line 91, in load_model
    modelCS = instantiate_from_config(config.modelCondStage)
  File "c:\users\serta\documents\stable-diffusion-ui\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "c:\users\serta\documents\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 262, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "c:\users\serta\documents\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 282, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "c:\users\serta\documents\stable-diffusion-ui\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "c:\users\serta\documents\stable-diffusion-ui\stable-diffusion\ldm\modules\encoders\modules.py", line 142, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File "C:\Users\serta\Documents\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\modeling_utils.py", line 1764, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "C:\Users\serta\Documents\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\models\clip\configuration_clip.py", line 126, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\serta\Documents\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\configuration_utils.py", line 553, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\serta\Documents\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\configuration_utils.py", line 652, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at 'C:\Users\serta/.cache\huggingface\transformers\9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142' is not a valid JSON file.

**Comment by FieserKiller** [comment]
exactly the same here

**Comment by deraishrike** [comment]
![Снимок](https://user-images.githubusercontent.com/113132314/189422513-91e46d3c-8f4d-48fc-bb71-602a2707bd0c.PNG)

**Comment by rredford** [comment]
I installed it, it ran great! Then next day I ran it again and have same issue as this one. Linux mint 10.3, it looks loaded and fine, but website stays at "Stable Diffusion UI is starting".

**Comment by rredford** [comment]
Oh I didn't get error till I tried to change settings. Now I get this

FileNotFoundError: [Errno 2] No such file or directory: '/home/rolf/Desktop/stable-diffusion-ui/ui/../scripts/config.json'

even if I start it again.

**Comment by FieserKiller** [comment]
This workaround helped, now progrm starts fine: https://github.com/cmdr2/stable-diffusion-ui/issues/131#issuecomment-1242339501

**Comment by Esfekia** [comment]
Thank you so much. I understand we are removing the commas, yes? and from where please?

**Comment by rredford** [comment]
hotfix fixed this!

**Comment by cmdr2** [comment]
Please restart your server, this issue has been fixed. Thanks
