### ISSUE TITLE
Install fails at dependency test on Ubuntu: libgomp-a34b3233.so.1

### ISSUE THREAD

**Issue by oyajiru** [cmdr2/stable-diffusion-ui#148]
Hi, I asked on Discord, but I think creating an issue here may be more appropriate. I removed everything and retried the installer from scratch, with the same results.

System: Ubuntu 22.04

Something to note though. I got this particular error after removing a previous torch install (through pip). Before that I got a more general message saying that not all dependencies were met for GFPGAN (sorry, can't reproduce this message).

I removed the whole thing, re-downloaded the release, unzipped and ran the installer again. This is the output I think would be most useful:

```
Installing pip dependencies: | Ran pip subprocess with arguments:
['/home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/env/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt']
Pip subprocess output:
Requirement already satisfied: imageio==2.9.0 in /home/user/.local/lib/python3.8/site-packages (from -r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 4)) (2.9.0)
Obtaining taming-transformers from git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers (from -r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 15))
  Cloning https://github.com/CompVis/taming-transformers.git (to revision master) to ./src/taming-transformers
Obtaining clip from git+https://github.com/openai/CLIP.git@main#egg=clip (from -r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 16))
  Cloning https://github.com/openai/CLIP.git (to revision main) to ./src/clip
Obtaining file:///home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion (from -r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 17))
Requirement already satisfied: torch in /home/user/.local/lib/python3.8/site-packages (from clip->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 16)) (1.8.1)
Requirement already satisfied: torchvision in ./env/lib/python3.8/site-packages (from clip->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 16)) (0.12.0)
Requirement already satisfied: numpy in /home/user/.local/lib/python3.8/site-packages (from latent-diffusion==0.0.1->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 17)) (1.21.2)
Collecting albumentations==0.4.3
  Using cached albumentations-0.4.3-py3-none-any.whl
Requirement already satisfied: scipy in /home/user/.local/lib/python3.8/site-packages (from albumentations==0.4.3->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 1)) (1.6.2)
Collecting einops==0.3.0
  Using cached einops-0.3.0-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: pillow in /home/user/.local/lib/python3.8/site-packages (from imageio==2.9.0->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 4)) (8.2.0)
Collecting imageio-ffmpeg==0.4.2
  Using cached imageio_ffmpeg-0.4.2-py3-none-manylinux2010_x86_64.whl (26.9 MB)
Collecting kornia==0.6
  Using cached kornia-0.6.0-py2.py3-none-any.whl (367 kB)
Collecting omegaconf==2.1.1
  Using cached omegaconf-2.1.1-py3-none-any.whl (74 kB)
Collecting opencv-python==4.1.2.30
  Using cached opencv_python-4.1.2.30-cp38-cp38-manylinux1_x86_64.whl (28.3 MB)
Collecting pudb==2019.2
  Using cached pudb-2019.2-py3-none-any.whl
Requirement already satisfied: pygments>=1.0 in /home/user/.local/lib/python3.8/site-packages (from pudb==2019.2->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 3)) (2.8.1)
Collecting pytorch-lightning==1.4.2
  Using cached pytorch_lightning-1.4.2-py3-none-any.whl (916 kB)
Requirement already satisfied: typing-extensions in ./env/lib/python3.8/site-packages (from pytorch-lightning==1.4.2->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 6)) (4.3.0)
Collecting torch-fidelity==0.3.0
  Using cached torch_fidelity-0.3.0-py3-none-any.whl (37 kB)
Collecting torchmetrics==0.6.0
  Using cached torchmetrics-0.6.0-py3-none-any.whl (329 kB)
Collecting transformers==4.19.2
  Using cached transformers-4.19.2-py3-none-any.whl (4.2 MB)
Requirement already satisfied: filelock in /home/user/.local/lib/python3.8/site-packages (from transformers==4.19.2->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 12)) (3.0.12)
Requirement already satisfied: requests in ./env/lib/python3.8/site-packages (from transformers==4.19.2->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 12)) (2.28.1)
Collecting antlr4-python3-runtime==4.8
  Using cached antlr4_python3_runtime-4.8-py3-none-any.whl
Collecting pyDeprecate==0.3.1
  Using cached pyDeprecate-0.3.1-py3-none-any.whl (10 kB)
Collecting streamlit>=0.73.1
  Using cached streamlit-1.12.2-py2.py3-none-any.whl (9.1 MB)
Requirement already satisfied: pandas>=0.21.0 in /home/user/.local/lib/python3.8/site-packages (from streamlit>=0.73.1->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 9)) (1.2.3)
Requirement already satisfied: importlib-metadata>=1.4 in /home/user/.local/lib/python3.8/site-packages (from streamlit>=0.73.1->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 9)) (4.8.0)
Requirement already satisfied: tornado>=5.0 in /home/user/.local/lib/python3.8/site-packages (from streamlit>=0.73.1->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 9)) (6.1)
Requirement already satisfied: protobuf<4,>=3.12 in /home/user/.local/lib/python3.8/site-packages (from streamlit>=0.73.1->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 9)) (3.15.7)
Collecting test-tube>=0.7.5
  Using cached test_tube-0.7.5-py3-none-any.whl
Collecting altair>=3.2.0
  Using cached altair-4.2.0-py3-none-any.whl (812 kB)
Requirement already satisfied: jsonschema>=3.0 in /home/user/.local/lib/python3.8/site-packages (from altair>=3.2.0->streamlit>=0.73.1->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 9)) (3.2.0)
Collecting blinker>=1.0.0
  Using cached blinker-1.5-py2.py3-none-any.whl (12 kB)
Collecting cachetools>=4.0
  Using cached cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting click>=7.0
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting fsspec[http]!=2021.06.0,>=2021.05.0
  Using cached fsspec-2022.8.2-py3-none-any.whl (140 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1
  Using cached aiohttp-3.8.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.3 MB)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in ./env/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning==1.4.2->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 6)) (2.0.4)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting attrs>=17.3.0
  Using cached attrs-22.1.0-py2.py3-none-any.whl (58 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.3.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (161 kB)
Collecting future>=0.17.1
  Using cached future-0.18.2-py3-none-any.whl
Collecting gitpython!=3.1.19
  Using cached GitPython-3.1.27-py3-none-any.whl (181 kB)
Collecting gitdb<5,>=4.0.1
  Using cached gitdb-4.0.9-py3-none-any.whl (63 kB)
Collecting huggingface-hub<1.0,>=0.1.0
  Using cached huggingface_hub-0.9.1-py3-none-any.whl (120 kB)
Collecting imgaug<0.2.7,>=0.2.5
  Using cached imgaug-0.2.6-py3-none-any.whl
Requirement already satisfied: six in ./env/lib/python3.8/site-packages (from imgaug<0.2.7,>=0.2.5->albumentations==0.4.3->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /home/user/.local/lib/python3.8/site-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit>=0.73.1->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 9)) (0.17.3)
Requirement already satisfied: setuptools in /home/user/.local/lib/python3.8/site-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit>=0.73.1->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 9)) (56.0.0)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (121 kB)
Collecting opencv-python-headless>=4.1.1
  Using cached opencv_python_headless-4.6.0.66-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (48.3 MB)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting pyarrow>=4.0
  Using cached pyarrow-9.0.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (35.3 MB)
Collecting pydeck>=0.1.dev5
  Using cached pydeck-0.8.0b3-py2.py3-none-any.whl (4.7 MB)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting pympler>=0.9
  Using cached Pympler-1.0.1-py3-none-any.whl (164 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting python-dateutil
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytz>=2017.3
  Using cached pytz-2022.2.1-py2.py3-none-any.whl (500 kB)
Collecting PyYAML
  Using cached PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
Collecting regex
  Downloading regex-2022.9.11-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (768 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/user/.local/lib/python3.8/site-packages (from requests->transformers==4.19.2->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 12)) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python3.8/site-packages (from requests->transformers==4.19.2->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 12)) (2022.6.15)
Requirement already satisfied: idna<4,>=2.5 in ./env/lib/python3.8/site-packages (from requests->transformers==4.19.2->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 12)) (3.3)
Collecting rich>=10.11.0
  Using cached rich-12.5.1-py3-none-any.whl (235 kB)
Collecting commonmark<0.10.0,>=0.9.0
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting scikit-image>=0.11.0
  Using cached scikit_image-0.19.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.0 MB)
Collecting networkx>=2.2
  Using cached networkx-2.8.6-py3-none-any.whl (2.0 MB)
Collecting PyWavelets>=1.1.1
  Using cached PyWavelets-1.3.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.9 MB)
Collecting smmap<6,>=3.0.1
  Using cached smmap-5.0.0-py3-none-any.whl (24 kB)
Collecting tensorboard>=2.2.0
  Using cached tensorboard-2.10.0-py3-none-any.whl (5.9 MB)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/user/.local/lib/python3.8/site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.4.2->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 6)) (0.4.4)
Requirement already satisfied: google-auth<3,>=1.6.3 in /home/user/.local/lib/python3.8/site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.4.2->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 6)) (1.28.0)
Requirement already satisfied: grpcio>=1.24.3 in /home/user/.local/lib/python3.8/site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.4.2->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 6)) (1.36.1)
Requirement already satisfied: wheel>=0.26 in ./env/lib/python3.8/site-packages (from tensorboard>=2.2.0->pytorch-lightning==1.4.2->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 6)) (0.37.1)
Collecting absl-py>=0.4
  Using cached absl_py-1.2.0-py3-none-any.whl (123 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/user/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning==1.4.2->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 6)) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/user/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning==1.4.2->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 6)) (4.7.2)
Collecting cachetools>=4.0
  Using cached cachetools-4.2.4-py3-none-any.whl (10 kB)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/user/.local/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.2.0->pytorch-lightning==1.4.2->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 6)) (1.3.0)
Collecting markdown>=2.6.8
  Using cached Markdown-3.4.1-py3-none-any.whl (93 kB)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/user/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning==1.4.2->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 6)) (0.4.8)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.2.1-py3-none-any.whl (151 kB)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Using cached tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
Collecting tifffile>=2019.7.26
  Using cached tifffile-2022.8.12-py3-none-any.whl (208 kB)
Collecting tokenizers!=0.11.3,<0.13,>=0.11.1
  Using cached tokenizers-0.12.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (6.6 MB)
Collecting tqdm
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting tzlocal>=1.1
  Using cached tzlocal-4.2-py3-none-any.whl (19 kB)
Collecting urwid>=1.1.1
  Using cached urwid-2.1.2-cp38-cp38-linux_x86_64.whl
Collecting validators>=0.2
  Using cached validators-0.20.0-py3-none-any.whl
Requirement already satisfied: decorator>=3.4.0 in /home/user/.local/lib/python3.8/site-packages (from validators>=0.2->streamlit>=0.73.1->-r /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/condaenv.r04fbzo6.requirements.txt (line 9)) (4.0.11)
Collecting werkzeug>=1.0.1
  Using cached Werkzeug-2.2.2-py3-none-any.whl (232 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.8.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (262 kB)
Collecting zipp>=0.5
  Using cached zipp-3.8.1-py3-none-any.whl (5.6 kB)
Collecting backports.zoneinfo
  Using cached backports.zoneinfo-0.2.1-cp38-cp38-manylinux1_x86_64.whl (74 kB)
Collecting entrypoints
  Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting ftfy
  Using cached ftfy-6.1.1-py3-none-any.whl (53 kB)
Collecting wcwidth>=0.2.5
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting pytz-deprecation-shim
  Using cached pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting semver
  Using cached semver-2.13.0-py2.py3-none-any.whl (12 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting toolz
  Using cached toolz-0.12.0-py3-none-any.whl (55 kB)
Collecting tzdata
  Using cached tzdata-2022.2-py2.py3-none-any.whl (336 kB)
Collecting watchdog
  Using cached watchdog-2.1.9-py3-none-manylinux2014_x86_64.whl (78 kB)
Installing collected packages: zipp, pyparsing, oauthlib, multidict, frozenlist, cachetools, yarl, tzdata, tifffile, smmap, PyWavelets, pytz, python-dateutil, packaging, networkx, MarkupSafe, backports.zoneinfo, attrs, async-timeout, aiosignal, werkzeug, wcwidth, tqdm, toolz, tensorboard-plugin-wit, tensorboard-data-server, scikit-image, PyYAML, pytz-deprecation-shim, markdown, jinja2, gitdb, fsspec, entrypoints, commonmark, aiohttp, absl-py, watchdog, validators, urwid, tzlocal, torchmetrics, toml, tokenizers, tensorboard, semver, rich, regex, pympler, pyDeprecate, pydeck, pyarrow, opencv-python-headless, imgaug, huggingface-hub, gitpython, future, ftfy, click, blinker, antlr4-python3-runtime, altair, transformers, torch-fidelity, test-tube, taming-transformers, streamlit, pytorch-lightning, pudb, opencv-python, omegaconf, latent-diffusion, kornia, imageio-ffmpeg, einops, clip, albumentations
  Running setup.py develop for taming-transformers
  Running setup.py develop for latent-diffusion
  Running setup.py develop for clip
Successfully installed MarkupSafe-2.1.1 PyWavelets-1.3.0 PyYAML-6.0 absl-py-1.2.0 aiohttp-3.8.1 aiosignal-1.2.0 albumentations-0.4.3 altair-4.2.0 antlr4-python3-runtime-4.8 async-timeout-4.0.2 attrs-22.1.0 backports.zoneinfo-0.2.1 blinker-1.5 cachetools-4.2.4 click-8.1.3 clip commonmark-0.9.1 einops-0.3.0 entrypoints-0.4 frozenlist-1.3.1 fsspec-2022.8.2 ftfy-6.1.1 future-0.18.2 gitdb-4.0.9 gitpython-3.1.27 huggingface-hub-0.9.1 imageio-ffmpeg-0.4.2 imgaug-0.2.6 jinja2-3.1.2 kornia-0.6.0 latent-diffusion markdown-3.4.1 multidict-6.0.2 networkx-2.8.6 oauthlib-3.2.1 omegaconf-2.1.1 opencv-python-4.1.2.30 opencv-python-headless-4.6.0.66 packaging-21.3 pudb-2019.2 pyDeprecate-0.3.1 pyarrow-9.0.0 pydeck-0.8.0b3 pympler-1.0.1 pyparsing-3.0.9 python-dateutil-2.8.2 pytorch-lightning-1.4.2 pytz-2022.2.1 pytz-deprecation-shim-0.1.0.post0 regex-2022.9.11 rich-12.5.1 scikit-image-0.19.3 semver-2.13.0 smmap-5.0.0 streamlit-1.12.2 taming-transformers tensorboard-2.10.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 test-tube-0.7.5 tifffile-2022.8.12 tokenizers-0.12.1 toml-0.10.2 toolz-0.12.0 torch-fidelity-0.3.0 torchmetrics-0.6.0 tqdm-4.64.1 transformers-4.19.2 tzdata-2022.2 tzlocal-4.2 urwid-2.1.2 validators-0.20.0 watchdog-2.1.9 wcwidth-0.2.5 werkzeug-2.2.2 yarl-1.8.1 zipp-3.8.1

done
#
# To activate this environment, use
#
#     $ conda activate /home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/env
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Retrieving notices: ...working... done
Installed. Testing..
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/torch/__init__.py", line 195, in <module>
    _load_global_deps()
  File "/home/user/.local/lib/python3.8/site-packages/torch/__init__.py", line 148, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/user/Downloads/stable-diffusion-ui-linux/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libgomp-a34b3233.so.1: cannot open shared object file: No such file or directory


Dependency test failed! Error installing the packages necessary for Stable Diffusion.
```

**Comment by oyajiru** [comment]
Solution found by the dev.

Apparently this issue is caused by Anaconda looking for stuff outside of the app's folder hierarchy. Do this:

Unzip from the downloaded zip (we're starting afresh), and run this command for the installer: PYTHONNOUSERSITE=1 ./start.sh 

That should force conda to ignore the /home/user/.local folder

The installer will be updated with this solution and this issue should be closed once that's done.

**Comment by cmdr2** [comment]
Thanks @oyajiru for your help in investigating this issue. The problem is conda linking with packages outside the conda environment, which can cause conflicts. https://github.com/cmdr2/stable-diffusion-ui/commit/ef46603f4ef4a8120d2232651bbaceb3420f69f2

The `PYTHONNOUSERSITE=1` environment variable is now set automatically by the installer, so no action is needed on the part of the users. Thanks!
