### ISSUE TITLE
ModuleNotFoundError: No module named 'gfpgan'

### ISSUE THREAD

**Issue by nightkall** [cmdr2/stable-diffusion-ui#179]
I get 'Error: The server is still starting up..' when I click Make Image the UI says 'Stable Diffusion has stopped'

In console:
```
Hotfixed broken JSON file from OpenAI
"Stable Diffusion's git repository was already installed. Updating.."
HEAD is now at d154155 Merge pull request #122 from ryudrigo/main
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

HEAD is now at d154155 Merge pull request #122 from ryudrigo/main
"Packages necessary for Stable Diffusion were already installed"
"Packages necessary for GFPGAN (Face Correction) were already installed"
"Packages necessary for ESRGAN (Resolution Upscaling) were already installed"
"Packages necessary for Stable Diffusion UI were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded"
"Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded"

"Stable Diffusion is ready!"

PYTHONPATH=C:\SD\cmdr2-stable-diffusion-ui\stable-diffusion;C:\SD\cmdr2-stable-diffusion-ui\stable-diffusion\env\Lib\site-packages
started in  C:\SD\cmdr2-stable-diffusion-ui\stable-diffusion
←[32mINFO←[0m:     Started server process [←[36m24408←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://0.0.0.0:9000←[0m (Press CTRL+C to quit)
Traceback (most recent call last):
  File "C:\SD\cmdr2-stable-diffusion-ui\ui\server.py", line 74, in ping
    from sd_internal import runtime
  File "C:\SD\cmdr2-stable-diffusion-ui\ui\sd_internal\runtime.py", line 19, in <module>
    from gfpgan import GFPGANer
ModuleNotFoundError: No module named 'gfpgan'

INFO:     127.0.0.1:50752 - "GET / HTTP/1.1" 200 OK
```

1. Open 'Start Stable Diffusion UI.cmd'
2. Click on 'Make Image'
3. See 'Error: The server is still starting up..'

**Screenshots**
https://imgur.com/W5szjF5

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Browser: Brave v1.43.89 Chromium to 105.0.5195.102

**Comment by internet-person** [comment]
same issue, win10 19044.1889, firefox 105.0.1

**Comment by JeLuF** [comment]
If you have moved your installation to a different folder or drive: The name of the installation folder is stored in many configuration files and moving it is therefore not possible. You can either move your installation back to the old place, or delete it and re-install to the new location.

**Comment by mantikafasi** [comment]
Open stable-diffusion-ui folder in vscode, press ctrl+shift+f and search old path (like "C:\Users","C://Users//username") and replace them with new path (to do this click to arrow on left and write new path)
Ex: "C:\Users" --> "D:\Users","C://Users//username" --> "D://Users"
