### ISSUE TITLE
Cuda out of memory

### ISSUE THREAD

**Issue by WereVrock** [cmdr2/stable-diffusion-ui#195]
Mostly when I try img to img I get cuda out of memory error:

I have 16 gb ram and nothing else open.

prompt: 3d render of a women playing with vr
    seed: 4365791
    num_inference_steps: 200
    guidance_scale: 7.5
    w: 512
    h: 512
    precision: autocast
    save_to_disk_path: None
    turbo: True
    use_cpu: False
    use_full_precision: True
    use_face_correction: GFPGANv1.3
    use_upscale: None
    show_only_filtered_image: True
    device cuda

    Using precision: full
Global seed set to 4365791
loaded input image of size (512, 512) from base64
Traceback (most recent call last):
  File "D:\downloads\stable-diffusion-ui-win64\stable-diffusion-ui\ui\server.py", line 110, in image
    res: Response = runtime.mk_img(r)
  File "D:\downloads\stable-diffusion-ui-win64\stable-diffusion-ui\ui\sd_internal\runtime.py", line 282, in mk_img
    modelFS.to(device)
  File "D:\downloads\stable-diffusion-ui-win64\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\pytorch_lightning\core\mixins\device_dtype_mixin.py", line 109, in to
    return super().to(*args, **kwargs)
  File "D:\downloads\stable-diffusion-ui-win64\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\module.py", line 907, in to
    return self._apply(convert)
  File "D:\downloads\stable-diffusion-ui-win64\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\module.py", line 578, in _apply
    module._apply(fn)
  File "D:\downloads\stable-diffusion-ui-win64\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\module.py", line 578, in _apply
    module._apply(fn)
  File "D:\downloads\stable-diffusion-ui-win64\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "D:\downloads\stable-diffusion-ui-win64\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\module.py", line 601, in _apply
    param_applied = fn(param)
  File "D:\downloads\stable-diffusion-ui-win64\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 4.10 GiB already allocated; 7.56 MiB free; 4.14 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

INFO:     127.0.0.1:64118 - "POST /image HTTP/1.1" 200 OK

**Comment by agentsimon** [comment]
Deselect the Turbo option

**Comment by jwax33** [comment]
CUDA out of memory errors typically refer to your video card ram not system ram.  Try deselecting the Turbo option and the Full Precision options.  Also make sure you are not running any programs in the background that eat up video ram.

**Comment by AlphaRayReal** [comment]
1.  it is not a Web UI bug.
2. It's not a bug at all - just a notification from Stable Diffusion (has nothing to do with Web UI)
3. you have not enough (free) VRAM to generate 512x512

- how much VRAM your nVidia Graphics card have?
- how much FREE dedicated VRAM is available?  (check this in Taskmanager)
