### ISSUE TITLE
Error at startup: "not enough memory"

### ISSUE THREAD

**Issue by elsucht** [cmdr2/stable-diffusion-ui#197]
**Describe the bug**
Initial startup of ui gives me error message in the console. Webui can be reached, Status is "stable-diffsusion has stopped".

**To Reproduce**
Double clic the cmd-file an wait

**Expected behavior**
The service starts, website is reachable and images can be generated.

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser: Chrome
 - RAM: 32 GB (20GB Free)
 - RTX 2080TI 11GB VRAM

**Additional context**
Error message in console:
```
←[32mINFO←[0m:     Started server process [←[36m49384←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://0.0.0.0:9000←[0m (Press CTRL+C to quit)
GPU detected:  NVIDIA GeForce RTX 2080 Ti
Loading model from sd-v1-4.ckpt
Global Step: 470000
UNet: Running in eps-prediction mode
Traceback (most recent call last):
  File "C:\stable-diffusion-ui\ui\server.py", line 75, in ping
    runtime.load_model_ckpt(ckpt_to_use="sd-v1-4")
  File "C:\stable-diffusion-ui\ui\sd_internal\runtime.py", line 111, in load_model_ckpt
    model = instantiate_from_config(config.modelUNet)
  File "C:\stable-diffusion-ui\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "C:\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 362, in __init__
    self.model1 = DiffusionWrapper(self.unetConfigEncode)
  File "C:\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 309, in __init__
    self.diffusion_model = instantiate_from_config(diff_model_config)
  File "C:\stable-diffusion-ui\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "C:\stable-diffusion-ui\stable-diffusion\optimizedSD\openaimodelSplit.py", line 572, in __init__
    ) if not use_spatial_transformer else SpatialTransformer(
  File "C:\stable-diffusion-ui\stable-diffusion\ldm\modules\attention.py", line 266, in __init__
    [BasicTransformerBlock(inner_dim, n_heads, d_head, dropout=dropout, context_dim=context_dim)
  File "C:\stable-diffusion-ui\stable-diffusion\ldm\modules\attention.py", line 266, in <listcomp>
    [BasicTransformerBlock(inner_dim, n_heads, d_head, dropout=dropout, context_dim=context_dim)
  File "C:\stable-diffusion-ui\stable-diffusion\ldm\modules\attention.py", line 225, in __init__
    self.attn1 = CrossAttention(query_dim=dim, heads=n_heads, dim_head=d_head, dropout=dropout)  # is a self-attention
  File "C:\stable-diffusion-ui\stable-diffusion\ldm\modules\attention.py", line 163, in __init__
    self.to_k = nn.Linear(context_dim, inner_dim, bias=False)
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch\nn\modules\linear.py", line 85, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 6553600 bytes.
```

**Comment by ikumi90s** [comment]
This happened to me so much, I feel like this is more on the 

"UNet: Running in eps-prediction mode"

after this has been added, even my 16GB systemram is chugging a lot and can quite kill my SSD faster that it should because it starts to write to the memory dump. it's just too big and can basically ended up "not enough memory" most of the time.

**Comment by cmdr2** [comment]
Hi, is this still an issue? We've fixed a lot of bugs since this issue was opened. Please try again (it'll auto-update if you run the program). If it continues to be an issue, please feel free to ask on Discord (https://discord.com/invite/u9yhsFmEkB) since the community there is a lot bigger and more responsive. Thanks!
