### ISSUE TITLE
OSError: Can't load the model for 'openai/clip-vit-large-patch14'

### ISSUE THREAD

**Issue by tyronx** [cmdr2/stable-diffusion-ui#201]
**Describe the bug**
First of all, thanks a lot for providing a 1-click installer for stable diffusion. Unfortunately I cannot get it to run - the server doesn't start up. In the web ui there is red text reading "Error: The server is still starting up."

**To Reproduce**
Run the .cmd command on windows 10 home.

**Desktop:**
 - OS: Windows 10 Home, 21H2
 - Browser: Firefox
 - Version: v2.05

**Additional context**

I ran the .cmd file around 4 times now, same error always. Startup log:

```
C:\stable-diffusion-ui>installer\Scripts\activate.bat
conda 4.14.0
git version 2.34.1.windows.1

(installer) C:\stable-diffusion-ui\installer\etc\conda\activate.d>cd C:\stable-diffusion-ui\installer\..\scripts

(installer) C:\stable-diffusion-ui\scripts>on_env_start.bat

"Stable Diffusion UI - v2"

"Stable Diffusion UI's git repository was already installed. Updating from main.."
HEAD is now at 1c5097b Hotfix for pywavelet version, attempt 1
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
sd-ui-files\ui\index.html
sd-ui-files\ui\modifiers.json
sd-ui-files\ui\server.py
sd-ui-files\ui\hotfix\9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142
sd-ui-files\ui\media\ding.mp3
sd-ui-files\ui\media\kofi.png
sd-ui-files\ui\sd_internal\ddim_callback.patch
sd-ui-files\ui\sd_internal\env_yaml.patch
sd-ui-files\ui\sd_internal\runtime.py
sd-ui-files\ui\sd_internal\__init__.py
10 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.

Hotfixed broken JSON file from OpenAI
"Stable Diffusion's git repository was already installed. Updating.."
HEAD is now at d154155 Merge pull request #122 from ryudrigo/main
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull  

HEAD is now at d154155 Merge pull request #122 from ryudrigo/main
"Packages necessary for Stable Diffusion were already installed"
"Packages necessary for GFPGAN (Face Correction) were already installed"
"Packages necessary for ESRGAN (Resolution Upscaling) were already installed"
"Packages necessary for Stable Diffusion UI were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded"
"Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded"

"Stable Diffusion is ready!"

PYTHONPATH=C:\stable-diffusion-ui\stable-diffusion;C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages
Python 3.8.5
started in  C:\stable-diffusion-ui\stable-diffusion
←[32mINFO←[0m:     Started server process [←[36m13972←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[[1mhttp://0.0.0.0:9000←[0m](http://paste.tyron.at/1mhttp://0.0.0.0:9000%E2%86%90[0m) (Press CTRL+C to quit)
GPU detected:  NVIDIA GeForce GTX 1060
Loading model from sd-v1-4.ckpt
Global Step: 470000
UNet: Running in eps-prediction mode
CondStage: Running in eps-prediction mode
Downloading:  14%|█████████▍                                                       | 236M/1.59G [03:21<18:43, 1.30MB/s]Traceback (most recent call last):
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\transformers\utils\hub.py", line 585, in get_from_cache
    http_get(url_to_download, temp_file, proxies=proxies, resume_size=resume_size, headers=headers)
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\transformers\utils\hub.py", line 440, in http_get
    temp_file.write(chunk)
  File "C:\stable-diffusion-ui\stable-diffusion\env\lib\tempfile.py", line 474, in func_wrapper
    return func(*args, **kwargs)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\transformers\modeling_utils.py", line 1852, in from_pretrained
    resolved_archive_file = cached_path(
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\transformers\utils\hub.py", line 282, in cached_path
    output_path = get_from_cache(
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\transformers\utils\hub.py", line 585, in get_from_cache
    http_get(url_to_download, temp_file, proxies=proxies, resume_size=resume_size, headers=headers)
  File "C:\stable-diffusion-ui\stable-diffusion\env\lib\tempfile.py", line 492, in __exit__
    result = self.file.__exit__(exc, value, tb)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-ui\ui\server.py", line 75, in ping
    runtime.load_model_ckpt(ckpt_to_use="sd-v1-4")
  File "C:\stable-diffusion-ui\ui\sd_internal\runtime.py", line 118, in load_model_ckpt
    modelCS = instantiate_from_config(config.modelCondStage)
  File "C:\stable-diffusion-ui\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "C:\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 262, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "C:\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 282, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "C:\stable-diffusion-ui\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "C:\stable-diffusion-ui\stable-diffusion\ldm\modules\encoders\modules.py", line 142, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\transformers\modeling_utils.py", line 1942, in from_pretrained
    raise EnvironmentError(
OSError: Can't load the model for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.

Downloading:  14%|█████████▍                                                       | 236M/1.59G [03:21<19:51, 1.23MB/s]
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: 
Traceback (most recent call last):
  File "C:\stable-diffusion-ui\stable-diffusion\env\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\stable-diffusion-ui\stable-diffusion\env\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
INFO:     127.0.0.1:50250 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:50250 - "GET /output_dir HTTP/1.1" 200 OK
INFO:     127.0.0.1:50250 - "GET /app_config HTTP/1.1" 200 OK
INFO:     127.0.0.1:50250 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:50250 - "GET /output_dir HTTP/1.1" 200 OK
INFO:     127.0.0.1:50250 - "GET /app_config HTTP/1.1" 200 OK
```

**Comment by tyronx** [comment]
ooof, i see the issue - `OSError: [Errno 28] No space left on device`
