### ISSUE TITLE
start.sh works only once

### ISSUE THREAD

**Issue by wITTus** [cmdr2/stable-diffusion-ui#220]
Hi,

**Describe the bug**
I can seem to only start the UI and the model server only one single time. After that, I get a stack trace from the server trying to launch the UI a second time.

I removed the entire directory and reinstalled completely from scratch, same behavior. Works only one time.

**To Reproduce**
1. Follow instructions for Linux by downloading https://github.com/cmdr2/stable-diffusion-ui/releases/download/v2.05/stable-diffusion-ui-linux.tar.xz
2. tar xvJf stable-diffusion-ui-linux.tar.xz
3. Run start.sh in the resulting directory
4. Wait until everything is installed
5. Enjoy the UI and the model (everything works perfectly fine)
6. CTRL+C in terminal to shutdown the server
7. Note some shell scripting errors... (see below)
8. Try to restart the server via start.sh
9. Get a stack trace... (see below)

**Expected behavior**
I'd expect that the server is running again, maybe also opening a browser tab again

**Screenshots**

Errors first run:

```
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [132529]
Press any key to continue
scripts/on_env_start.sh: line 42: unexpected EOF while looking for matching `"'
scripts/on_env_start.sh: line 43: syntax error: unexpected end of file
./start.sh: line 6: env_start.sh: command not found
```

That's weird because I don't see any missing quotes at these lines in `on_env_start.sh` (also I didn't touch any files):

```
41 ./scripts/on_sd_start.sh
42 
43 read -p "Press any key to continue"
```

Stacktrace second run:

```
foobar@foobar-ryzen:~/projects/stable-diffusion/stable-diffusion-ui$ ./start.sh


Stable Diffusion UI

Stable Diffusion UI's git repository was already installed. Updating from beta..
HEAD is now at 16c8423 Don't apply filters if the user stops a task
Already on 'beta'
Your branch is up to date with 'origin/beta'.
Already up to date.

Hotfixed broken JSON file from OpenAI
Stable Diffusion's git repository was already installed. Updating..
HEAD is now at d154155 Merge pull request #122 from ryudrigo/main
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

HEAD is now at d154155 Merge pull request #122 from ryudrigo/main
Packages necessary for Stable Diffusion were already installed
Packages necessary for ESRGAN (Resolution Upscaling) were already installed
Packages necessary for Stable Diffusion UI were already installed
Data files (weights) necessary for Stable Diffusion were already downloaded
Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded
Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded
Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded


Stable Diffusion is ready!

PYTHONPATH=/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion;/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages
Python 3.8.5
started in  /home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion
Traceback (most recent call last):
  File "/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion/env/bin/uvicorn", line 11, in <module>
    sys.exit(main())
  File "/home/foobar/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/foobar/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/foobar/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/foobar/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/uvicorn/main.py", line 408, in main
    run(
  File "/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/foobar/projects/stable-diffusion/stable-diffusion-ui/ui/server.py", line 17, in <module>
    from fastapi import FastAPI, HTTPException
  File "/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/fastapi/applications.py", line 15, in <module>
    from fastapi import routing
  File "/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/fastapi/routing.py", line 22, in <module>
    from fastapi.datastructures import Default, DefaultPlaceholder
  File "/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/fastapi/datastructures.py", line 3, in <module>
    from starlette.datastructures import URL as URL  # noqa: F401
  File "/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/starlette/datastructures.py", line 7, in <module>
    from starlette.concurrency import run_in_threadpool
  File "/home/foobar/projects/stable-diffusion/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/starlette/concurrency.py", line 11, in <module>
    from typing_extensions import ParamSpec
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/home/foobar/.local/lib/python3.8/site-packages/typing_extensions.py)
Press any key to continue
Press any key to continue
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - Browser: Mozilla Firefox
 - Version: 104.0

**Additional context**

I tried the "beta" mode in the second run, but same result.

Also, I want to thank you and everyone else working on this. Incredible how easy the installation is.

Best Regards,
Sascha

**Comment by wITTus** [comment]
I found the problem.

Locally, I had `typing-extensions-3.7.4.3` installed.

Uninstalling the package solved the problem.

**Comment by cmdr2** [comment]
Thanks! We added the `PYTHONNOUSERBASE=1` a while ago, I think that achieves the same result.
