### ISSUE TITLE
"Potential NSFW content" on the default prompt.

### ISSUE THREAD

**Issue by UrielCh** [cmdr2/stable-diffusion-ui#23]
## Configuration:
Windows 11
CPU: AMD Ryzen 5 5600X
Memory: 64GB
WSL2 + ubuntu 22.04.1
GPU: GeForce GTX 1660 SUPER
GPU Memory: 6GB

```bash
docker run --rm -it --gpus=all nvcr.io/nvidia/k8s/cuda-sample:nbody nbody -gpu -benchmark
> Windowed mode
> Simulation data stored in video memory
> Single precision floating point simulation
> 1 Devices used for simulation
GPU Device 0: "Turing" with compute capability 7.5

> Compute 7.5 CUDA device: [NVIDIA GeForce GTX 1660 SUPER]
22528 bodies, total time for 10 iterations: 32.767 ms
= 154.884 billion interactions per second
= 3097.676 single-precision GFLOP/s at 20 flops per interaction
```

## Error message:
```
sd                                    | Using seed: 922
50it [00:32,  1.56it/s]               |
sd                                    | Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
sd                                    | INFO:     172.18.0.4:36142 - "POST /predictions HTTP/1.1" 500 Internal Server Error
sd                                    | ERROR:    Exception in ASGI application
sd                                    | Traceback (most recent call last):
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
sd                                    |     result = await app(self.scope, self.receive, self.send)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
sd                                    |     return await self.app(scope, receive, send)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
sd                                    |     await super().__call__(scope, receive, send)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
sd                                    |     await self.middleware_stack(scope, receive, send)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
sd                                    |     raise exc
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
sd                                    |     await self.app(scope, receive, _send)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
sd                                    |     raise exc
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
sd                                    |     await self.app(scope, receive, sender)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
sd                                    |     raise e
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
sd                                    |     await self.app(scope, receive, send)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
sd                                    |     await route.handle(scope, receive, send)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
sd                                    |     await self.app(scope, receive, send)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
sd                                    |     response = await func(request)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
sd                                    |     raw_response = await run_endpoint_function(
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
sd                                    |     return await run_in_threadpool(dependant.call, **values)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
sd                                    |     return await anyio.to_thread.run_sync(func, *args)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
sd                                    |     return await get_asynclib().run_sync_in_worker_thread(
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
sd                                    |     return await future
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
sd                                    |     result = context.run(func, *args)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/cog/server/http.py", line 79, in predict
sd                                    |     output = predictor.predict(**request.input.dict())
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
sd                                    |     return func(*args, **kwargs)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
sd                                    |     return func(*args, **kwargs)
sd                                    |   File "/src/predict.py", line 113, in predict
sd                                    |     raise Exception("NSFW content detected, please try a different prompt")
sd                                    | Exception: NSFW content detected, please try a different prompt
sd-ui                                 | INFO:     172.18.0.1:34184 - "POST /image HTTP/1.1" 500 Internal Server Error
```

I get the error with the default prompt: "a photograph of an astronaut riding a horse"
I tried with 256x256 image size, and I get the same error.

**Comment by ChrisAcrobat** [comment]
Fun! What where your settings (seed, e.t.c.)?
The message is sent from [replicate/cog-stable-diffusion](https://github.com/replicate/cog-stable-diffusion/blob/main/predict.py#L113).

**Comment by cmdr2** [comment]
Yeah, I've seen that 256x256 with could trigger that warning. Try 512x512 (if you can), and/or try increasing your iteration count.

**Comment by UrielCh** [comment]
I tried 256x256 and 512x512 and get the same error (with a different seed of course)

adding the seed in the log, was a nice move 👍

**Comment by UrielCh** [comment]
A last tries:
Using seed: 3306
size: 512x512
Number of inference steps: 50 => 100
...
 Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.

same error.

**Comment by onduboy** [comment]
I have the same problem.
Try differents prompts, random seeds, all widths and heights and steps from 50 to 150. But I continue to receive the NSFW warning.

**Setup**
Windows 10
CPU: AMD Ryzen 7 2700
Memory: 32GB
WSL2 + ubuntu 20.04.4
GPU: GeForce GTX 1660 OC
GPU Memory: 6GB

```
Using seed: 3521
100it [04:48,  2.89s/it]
sd                    | Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
sd                    | INFO:     172.18.0.4:52430 - "POST /predictions HTTP/1.1" 500 Internal Server Error
sd                    | ERROR:    Exception in ASGI application
sd                    | Traceback (most recent call last):
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
sd                    |     result = await app(self.scope, self.receive, self.send)
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
sd                    |     return await self.app(scope, receive, send)
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
sd                    |     await super().__call__(scope, receive, send)
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
sd                    |     await self.middleware_stack(scope, receive, send)
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
sd                    |     raise exc
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
sd                    |     await self.app(scope, receive, _send)
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
sd                    |     raise exc
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
sd                    |     await self.app(scope, receive, sender)
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
sd                    |     raise e
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
sd                    |     await self.app(scope, receive, send)
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
sd                    |     await route.handle(scope, receive, send)
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
sd                    |     await self.app(scope, receive, send)
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
sd                    |     response = await func(request)
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
sd                    |     raw_response = await run_endpoint_function(
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
sd                    |     return await run_in_threadpool(dependant.call, **values)
sd-ui                 | INFO:     172.18.0.1:46902 - "POST /image HTTP/1.1" 500 Internal Server Error
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
sd                    |     return await anyio.to_thread.run_sync(func, *args)
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
sd                    |     return await get_asynclib().run_sync_in_worker_thread(
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
sd                    |     return await future
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
sd                    |     result = context.run(func, *args)
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/cog/server/http.py", line 79, in predict
sd                    |     output = predictor.predict(**request.input.dict())
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
sd                    |     return func(*args, **kwargs)
sd                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
sd                    |     return func(*args, **kwargs)
sd                    |   File "/src/predict.py", line 113, in predict
sd                    |     raise Exception("NSFW content detected, please try a different prompt")
sd                    | Exception: NSFW content detected, please try a different prompt
```

**Comment by cmdr2** [comment]
Hi @onduboy @UrielCh can you please try changing `docker-compose.yml` with this image version? `r8.im/stability-ai/stable-diffusion@sha256:3080f37ef32771c9984d65033cbe71caa96c69680008bae64cf691724a6df04c` instead of what's there.

And then `docker-compose down` and `docker-compose up &` to restart the server.

Thanks

**Comment by zaqxs123456** [comment]
Can we edit the stable diffusion source code and run it on this UI so that we will not have any prompt limitation?

**Comment by UrielCh** [comment]
2.571GB layer update later:

```
Using seed: 5362
58it [00:37,  1.54it/s]               | 
sd                                    | Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
sd                                    | INFO:     172.18.0.4:37010 - "POST /predictions HTTP/1.1" 500 Internal Server Error
sd                                    | ERROR:    Exception in ASGI application
sd                                    | Traceback (most recent call last):
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
sd                                    |     result = await app(self.scope, self.receive, self.send)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
sd                                    |     return await self.app(scope, receive, send)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
sd                                    |     await super().__call__(scope, receive, send)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
sd                                    |     await self.middleware_stack(scope, receive, send)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
sd                                    |     raise exc
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
sd                                    |     await self.app(scope, receive, _send)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
sd                                    |     raise exc
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
sd                                    |     await self.app(scope, receive, sender)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
sd                                    |     raise e
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
sd                                    |     await self.app(scope, receive, send)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
sd                                    |     await route.handle(scope, receive, send)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
sd                                    |     await self.app(scope, receive, send)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
sd                                    |     response = await func(request)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
sd                                    |     raw_response = await run_endpoint_function(
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
sd                                    |     return await run_in_threadpool(dependant.call, **values)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
sd                                    |     return await anyio.to_thread.run_sync(func, *args)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
sd                                    |     return await get_asynclib().run_sync_in_worker_thread(
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
sd                                    |     return await future
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
sd                                    |     result = context.run(func, *args)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/cog/server/http.py", line 79, in predict
sd                                    |     output = predictor.predict(**request.input.dict())
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
sd                                    |     return func(*args, **kwargs)
sd                                    |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
sd                                    |     return func(*args, **kwargs)
sd                                    |   File "/src/predict.py", line 100, in predict
sd                                    |     raise Exception("NSFW content detected, please try a different prompt")
```

**Comment by Sparkenstein** [comment]
>  can you please try changing docker-compose.yml to this image version

The given link is returning 404. do we need to be logged in or something to get that? 
I am also facing the same error.

 I only followed following steps:
 - `git clone url`
 - `docker-compose up`
 
My prompt was: "artistic drawing of a a man floating in space"

**Comment by cmdr2** [comment]
@UrielCh @zaqxs123456 @onduboy @ChrisAcrobat  I'm working on an update that installs the regular Stable Diffusion git repository, in which case you should be able to bypass this error if you want. It requires zero setup, just download and run, and it'll automatically download+install everything behind the scenes. No WSL required either.

I'm planning to check it into a branch so that it can be tried out, should be there shortly. At present I have it working on Windows, but the technique should work on Linux/Mac as well.

But in the meanwhile, can you please try this config and let me know you're still getting NSFW warnings?
```
Prompt: "a photograph of an astronaut riding a horse"
Seed: 6069
Num Outputs: 1, parallel: 1 image at a time
Width and Height: 512
Num Inference Steps: 50
Guidance Scale: 7.5
```

Thanks

**Comment by UrielCh** [comment]
with the original docker-compose or the on with `r8.im/stability-ai/stable-diffusion@sha256:3080f37ef32771c9984d65033cbe71caa96c69680008bae64cf691724a6df04c` ?

**Comment by cmdr2** [comment]
@UrielCh Either version generates a result for me, so you can try with whichever version's installed. Thanks

**Comment by UrielCh** [comment]
Sorry for the delay, I'm working on a muti-arch Kubernetes port, which makes me crazy. Working on Pi-4 as only ARM64 arch is soooo   slowwwwww.


Git new content pulled.
![image](https://user-images.githubusercontent.com/6543761/187200484-ec104961-5bd8-46ca-b668-e018f7820192.png)



```
sd                     | Using seed: 6069
50it [02:50,  3.40s/it]| 
sd                     | Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
sd                     | INFO:     172.19.0.3:41056 - "POST /predictions HTTP/1.1" 500 Internal Server Error
sd                     | ERROR:    Exception in ASGI application
sd                     | Traceback (most recent call last):
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
sd                     |     result = await app(self.scope, self.receive, self.send)
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
sd                     |     return await self.app(scope, receive, send)
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
sd                     |     await super().__call__(scope, receive, send)
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
sd                     |     await self.middleware_stack(scope, receive, send)
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
sd                     |     raise exc
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
sd                     |     await self.app(scope, receive, _send)
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
sd                     |     raise exc
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
sd                     |     await self.app(scope, receive, sender)
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
sd                     |     raise e
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
sd                     |     await self.app(scope, receive, send)
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
sd                     |     await route.handle(scope, receive, send)
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
sd                     |     await self.app(scope, receive, send)
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
sd                     |     response = await func(request)
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
sd                     |     raw_response = await run_endpoint_function(
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
sd                     |     return await run_in_threadpool(dependant.call, **values)
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
sd                     |     return await anyio.to_thread.run_sync(func, *args)
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
sd                     |     return await get_asynclib().run_sync_in_worker_thread(
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
sd                     |     return await future
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
sd                     |     result = context.run(func, *args)
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/cog/server/http.py", line 79, in predict
sd                     |     output = predictor.predict(**request.input.dict())
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
sd                     |     return func(*args, **kwargs)
sd                     |   File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
sd                     |     return func(*args, **kwargs)
sd                     |   File "/src/predict.py", line 113, in predict
sd                     |     raise Exception("NSFW content detected, please try a different prompt")
sd                     | Exception: NSFW content detected, please try a different prompt
sd-ui                  | INFO:     172.19.0.1:48150 - "POST /image HTTP/1.1" 500 Internal Server Error
```

**Comment by onduboy** [comment]
@cmdr2, thanks for your work
> I'm working on an update that installs the regular Stable Diffusion git repository, in which case you should be able to bypass this error if you want. It requires zero setup, just download and run, and it'll automatically download+install everything behind the scenes. No WSL required either.

I try this with both docker image versions but still get the NSWF warning

> ```
> Prompt: "a photograph of an astronaut riding a horse"
> Seed: 6069
> Num Outputs: 1, parallel: 1 image at a time
> Width and Height: 512
> Num Inference Steps: 50
> Guidance Scale: 7.5
> ```

**Comment by cmdr2** [comment]
@onduboy @UrielCh @ChrisAcrobat @zaqxs123456  I'm sorry, I'd just say, please try the new version that's coming out soon. It'll have a flag to disable NSFW warnings, so hopefully that'll work better for you.

I'm finishing up the new version as we speak.

I would be very grateful if you could please try the new version. If you're willing, can you please send me an email to sd@cmdr2.org, so that I can send you a test version, as soon as it's ready?

Thanks again, and I appreciate your patience with this.

**Comment by lstewart15** [comment]
Having the same issues here... interestingly also using a 1660  (Ti though) with 6GB -- no matter what the prompt/image size/iterations, get NSFW and no result.

**Comment by UrielCh** [comment]
Hi,

After some new test following: [this doc](https://rentry.org/GUItard)
I end with green screens
Looking for details about this issue, I found [this issue](https://github.com/CompVis/stable-diffusion/issues/69)
Talking about Getting NaN result to internal computation.
Nan Result was my last issue with my [YOLOv3 Object Detector - Snowman](https://github.com/UrielCh/opencv4nodejs/tree/master/examples/src/YOLOv3-Training-Snowman-Detector)
 code port.

So... 

The issue comes from the 1660 card. It should work with full precision to fix the problem but requires twice the memory.
So my 1660 with ^GB VRAM should be able to generate 256x512 images in full precisions.

Please [cmdr2](https://github.com/cmdr2), can you add an option to use full precisions and check if the first cell in the output result contains NaN? If that is the case, the GPU can not correctly handle fp16 operations.

**Comment by cmdr2** [comment]
@UrielCh Thanks, that's useful. I think I can do that.

The v2 test build I shared yesterday (#26) works on full precision, it is running an unmodified Stable Diffusion code. If you get a chance, it would be useful to know if that fixes that problem. Thanks!

**Comment by UrielCh** [comment]
GPU shortage is over, It's time to upgrade.
`3060 12GB` or `3060Ti 8GB`, I think more VRAM is more useful than more Horsepower, and I Prefer not upgrading my Power supply (650W)

**Comment by cmdr2** [comment]
@UrielCh I recently upgraded to a 3060 12GB, Stable Diffusion works well on it. The 12GB is not 2x better, because the memory address width is still the same, so it will be bottlenecked a bit. But it's definitely able to handle Stable Diffusion with no optimizations.

**Comment by cmdr2** [comment]
@UrielCh The [issue you linked to](https://github.com/CompVis/stable-diffusion/issues/69) suggests using basujindal's optimized script with `--precision full`, and I've actually been looking at that. I've been reading its code, with the intention of using that fork in v2 instead of the stock Stable Diffusion (used currently). Maybe that'll help.

**Comment by UrielCh** [comment]
I'm expected to be able to load future large models with a 12 GB.
a 3060 12GB will be slower, but more capable than a 3080 8GB, Am I right?

**Comment by UrielCh** [comment]
Thx for this new build, but I drop my 1660 out of my PC, I can no longer test it.
My GFX is now a 3060 12GB

**Comment by cmdr2** [comment]
@UrielCh Nice! :) Welcome to the 3060 family! No problem, if you do get a chance to run the new v2 build, it runs much faster than v1, for large batches.

I was previously able to generate just 4 images in parallel (with my 3060 12GB), now the number is much higher.
