### ISSUE TITLE
Error on startup when no internet/network conection. Offline needs/needed.

### ISSUE THREAD

**Issue by maikelsz** [cmdr2/stable-diffusion-ui#248]
Bug, or Enhancement needed?

On boot SD, the latest version is now crashing if there is no internet connection. The previous version worked for me without problems even without connection (or so it seemed), but today it was auto-updated and now an error appears. Before, I didn't use a proxy to be able to install SD (the installer don´t support proxies, as I see). but then I was using it with proxy and also using it offline. Now it tries to get something from the web, apparently from huggingface web site, something that was not necessary before.

right after the line "CondStage: Running in eps-prediction mode" the console spits this:

Traceback (most recent call last):
  File "f:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "f:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "f:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "f:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "f:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "f:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001EF6DF114F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "f:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "f:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /openai/clip-vit-large-patch14/resolve/main/vocab.json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EF6DF114F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\stable-diffusion-ui\ui\server.py", line 86, in ping
    runtime.load_model_ckpt(ckpt_to_use="sd-v1-4")
  File "f:\stable-diffusion-ui\ui\sd_internal\runtime.py", line 120, in load_model_ckpt
    modelCS = instantiate_from_config(config.modelCondStage)
  File "f:\stable-diffusion-ui\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "f:\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 262, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "f:\stable-diffusion-ui\stable-diffusion\optimizedSD\ddpm.py", line 282, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "f:\stable-diffusion-ui\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "f:\stable-diffusion-ui\stable-diffusion\ldm\modules\encoders\modules.py", line 141, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(version)
  File "f:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\transformers\tokenization_utils_base.py", line 1723, in from_pretrained
    resolved_vocab_files[file_id] = cached_path(
  File "f:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\transformers\utils\hub.py", line 282, in cached_path
    output_path = get_from_cache(
  File "f:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\transformers\utils\hub.py", line 485, in get_from_cache
    r = requests.head(url, headers=headers, allow_redirects=False, proxies=proxies, timeout=etag_timeout)
  File "f:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\requests\api.py", line 100, in head
    return request("head", url, **kwargs)
  File "f:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "f:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "f:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "f:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /openai/clip-vit-large-patch14/resolve/main/vocab.json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EF6DF114F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))

Something necessary at startup, because after that, you can pull the cable and it still works

Is there any way to do a downgrade to the previous version, or to keep what this new version needs now from the web cached locally? 

A way to be able to use it behind proxies (and a proxy option is needed anyway I think) or completely offline (I think this is  more important)?

**Comment by cmdr2** [comment]
Hi, I just tested on my PC after turning off the internet connection, and it ran alright. I was able to start it up, and generate an image completely offline.

My suggestion is to let it connect to the internet once, to let it download the file from HuggingFace. And I think it'll then continue working offline after that.

Unfortunately, our project is just a UI and Installer over Stable Diffusion, and there are a lot of places in Stable Diffusion's code where it tries to download updated weights. And it is beyond the scope of this project to alter how Stable Diffusion works.

So please try my suggestion, to connect and let it download that weight. And after that you can try turning off the internet again.

It is probably a coincidence that yesterday's update changed things, because nothing related to stable diffusion was released yesterday. The code you're referring to is the Stable Diffusion code that we never touch.

Thanks! Please re-open or ask on #suport in the Discord group (https://discord.com/invite/u9yhsFmEkB) if this issue continues after connecting back to the internet once.

**Comment by maikelsz** [comment]
after this, some update manage to cache or something the file it was looking on the web. now it starts offline.
will test something about conda to see if I can copy and run on different PCs, so I don't need to download everything in everyone, juts update in on PC and copy to the rest

**Comment by maikelsz** [comment]
not working offline again at startup. I´ll try to find what is it. what remains on the PC, to make it work
