### ISSUE TITLE
I meet a bug when i am installing. ( Obtaining taming-transformers failed.)

### ISSUE THREAD

**Issue by mx597014232** [cmdr2/stable-diffusion-ui#287]
env :win10

\ Ran pip subprocess with arguments:
['D:\\stable-diffusion-ui\\stable-diffusion\\env\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'D:\\stable-diffusion-ui\\stable-diffusion\\condaenv.02e1t87w.requirements.txt']
Pip subprocess output:
Obtaining taming-transformers from git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers (from -r D:\stable-diffusion-ui\stable-diffusion\condaenv.02e1t87w.requirements.txt (line 17))

Pip subprocess error:
ERROR: Exception:
Traceback (most recent call last):
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'taming-transformers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_internal\vcs\git.py", line 322, in get_remote_url
    found_remote = remotes[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_internal\cli\base_command.py", line 224, in _main
    status = self.run(options, args)
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_internal\cli\req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_internal\commands\install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 310, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 79, in from_requirement
    cands = build_iter_view(provider.find_matches([requirement]))
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 148, in build_iter_view
    matches = list(matches)
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 255, in <genexpr>
    if constraint.is_satisfied_by(c)
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_internal\resolution\resolvelib\base.py", line 66, in is_satisfied_by
    return self.specifier.contains(candidate.version, prereleases=True)
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 194, in version
    self._version = self.dist.parsed_version
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 239, in dist
    self._prepare()
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 346, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_internal\operations\prepare.py", line 573, in prepare_editable_requirement
    req.update_editable(self.download_dir is None)
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_internal\req\req_install.py", line 655, in update_editable
    vcs_backend.obtain(self.source_dir, url=hidden_url)
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 654, in obtain
    existing_url = self.get_remote_url(dest)
  File "D:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\pip\_internal\vcs\git.py", line 324, in get_remote_url
    raise RemoteNotFoundError
pip._internal.vcs.versioncontrol.RemoteNotFoundError

failed

CondaEnvException: Pip failed

"Error installing the packages necessary for Stable Diffusion. Sorry about that, please try to:"
"  1. Run this installer again."
"  2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/blob/main/Troubleshooting.md"
"  3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB"
"  4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues"
"Thanks!"

**Comment by maikelsz** [comment]
that happened to me once, in this or another project with SD
If I remember correctly, I solved it by cloning the project directly.
go to the folder : stable-diffusion\src\
and run: git clone https://github.com/CompVis/taming-transformers.git

**Comment by mx597014232** [comment]
I try it, but it doesn't work.
I give up.

**Comment by cmdr2** [comment]
Can you please try with the latest installer (we released a new version a few days ago): https://github.com/cmdr2/stable-diffusion-ui#installation

Please feel free to ask on our Discord server if this continues to be an issue, it'll be a bit faster in terms of response due to a larger community being present there: https://discord.com/invite/u9yhsFmEkB

Thanks!
