### ISSUE TITLE
Does not support multiple tabs

### ISSUE THREAD

**Issue by ChrisAcrobat** [cmdr2/stable-diffusion-ui#290]
**Describe the bug**
Based on the  console output, if I have open two tabs and queues two generations at the same time, both of them will be executed at the same time which results in one of the images to crash due to out of memory. And sometimes resulting in a hard crash that requires a server restart.
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\starlette\routing.py", line 680, in __call__    await route.handle(scope, receive, send)
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\starlette\routing.py", line 68, in app
    await response(scope, receive, send)
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\starlette\responses.py", line 273, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\starlette\responses.py", line 269, in wrap
    await func()
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\starlette\responses.py", line 258, in stream_response
    async for chunk in self.body_iterator:
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\starlette\concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\starlette\concurrency.py", line 53, in _next    return next(iterator)
  File "D:\stable-diffusion-ui-cmdr2\ui\sd_internal\runtime.py", line 194, in mk_img
    gc()
  File "D:\stable-diffusion-ui-cmdr2\ui\sd_internal\runtime.py", line 583, in gc
    torch.cuda.empty_cache()
  File "D:\stable-diffusion-ui-cmdr2\stable-diffusion\env\Lib\site-packages\torch\cuda\memory.py", line 114, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**To Reproduce**
1. Start server.
2. Open two tabs.
3. Click on `Make image` on both tabs.

**Expected behavior**
Two images should be returned when they are done.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: v2.195

**Additional context**
In version 1 images was generated in sequence on the server, not parallel. I would like this feature back so I can generate multiple different themes of images at the same time. 🙂
If the server could return number of queued request, then that would be a great addition, so I could see wish should be done next.

**Comment by cmdr2** [comment]
Hi, multiple tabs aren't a supported behavior. :) While I'm not against fixing this problem, I'm curious to know why you need multiple tabs filing requests? Thanks

**Comment by ChrisAcrobat** [comment]
Mainly when I playing around with phrases and comes up with a new spin or idea I open a new tab an with that, while still have the previous idea(s) in older tabs and making smaller changes or just different seeds.
For instance, say that I'm playing around with "diesel powered dinosaurs" and then I want to see what "dinosaurs on mars" generate, while also what to see what "diesel powered dinosaurs jet engines" returns. Then I'll modify the prompt and add "with jet engines" and separately open a new tab and enters "dinosaurs on mars". So now I don't need to replace the whole prompt when I want to experiment with the two different prompts.
Also, this would enable me to share my instance over the LAN so my family also could generate images when I do.

In theory I don't think this should be a complex task. Would you accept an PR if I would take on the challenge?
_Note: I'm not promising any deadlines because I also have other stuff to do. 😄_

**Comment by JeLuF** [comment]
@ChrisAcrobat, support for multiple tabs has been added a while ago. Can this ticket be closed, or is there still something missing?

**Comment by ChrisAcrobat** [comment]
Oh, I haven't noticed! Thanks for the heads up.
After a quick test it looks like it's working perfectly. 👍

**Comment by bpaq3** [comment]
@cmdr2 I am actually running into the same problem now => Connection Errored Out

OS: Windows 10 x64
Browser: Chrome
Version: Latest as of Post
