### ISSUE TITLE
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution

### ISSUE THREAD

**Issue by ItsMichaelll** [cmdr2/stable-diffusion-ui#30]
Installation was successful, UI works, but when I try to generate an image I get the error

RuntimeError: Unable to find a valid cuDNN algorithm to run convolution

Here is the output:

`Traceback (most recent call last):
  File "C:\stable-diffusion-ui\stable-diffusion\..\ui\server.py", line 85, in image
    res: Response = runtime.mk_img(r)
  File "C:\stable-diffusion-ui\stable-diffusion\..\ui\sd_internal\runtime.py", line 121, in mk_img
    x_samples = _txt2img(opt_W, opt_H, opt_n_samples, opt_ddim_steps, opt_scale, None, opt_C, opt_f, opt_ddim_eta, c, uc)
  File "C:\stable-diffusion-ui\stable-diffusion\..\ui\sd_internal\runtime.py", line 147, in _txt2img
    samples_ddim, _ = sampler.sample(S=opt_ddim_steps,
  File "C:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "c:\stable-diffusion-ui\stable-diffusion\ldm\models\diffusion\plms.py", line 97, in sample
    samples, intermediates = self.plms_sampling(conditioning, size,
  File "C:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "c:\stable-diffusion-ui\stable-diffusion\ldm\models\diffusion\plms.py", line 152, in plms_sampling
    outs = self.p_sample_plms(img, cond, ts, index=index, use_original_steps=ddim_use_original_steps,
  File "C:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "c:\stable-diffusion-ui\stable-diffusion\ldm\models\diffusion\plms.py", line 218, in p_sample_plms
    e_t = get_model_output(x, t)
  File "c:\stable-diffusion-ui\stable-diffusion\ldm\models\diffusion\plms.py", line 185, in get_model_output
    e_t_uncond, e_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)
  File "c:\stable-diffusion-ui\stable-diffusion\ldm\models\diffusion\ddpm.py", line 987, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\stable-diffusion-ui\stable-diffusion\ldm\models\diffusion\ddpm.py", line 1410, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\stable-diffusion-ui\stable-diffusion\ldm\modules\diffusionmodules\openaimodel.py", line 732, in forward
    h = module(h, emb, context)
  File "C:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\stable-diffusion-ui\stable-diffusion\ldm\modules\diffusionmodules\openaimodel.py", line 87, in forward
    x = layer(x)
  File "C:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\torch\nn\modules\conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\torch\nn\modules\conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution`

**Comment by cmdr2** [comment]
Hi @ItsMichaelll , sorry for the late reply. I've updated the v2 version with a new build. It has a few more checks that it performs after installation, to make sure everything necessary is downloaded automatically.

You can download it from https://drive.google.com/file/d/1cEuOcb9OaldXcc2XzEMqEdvAr_w-KJ_p/view?usp=sharing and then double-click `Start Stable Diffusion UI.cmd` to install and run.

Please let me know if there are any problems after running it.

PS: There's a new Discord server for support and development discussions: https://discord.com/invite/u9yhsFmEkB . Please join in for faster discussion and feedback on v2. Thanks!

**Comment by cmdr2** [comment]
Closing this, please re-open if this is still an issue. The latest installer has a lot of checks, so I'd suggest running that. Thanks
