### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by Atomica1** [cmdr2/stable-diffusion-ui#31]
python is installed and updated and so is opencv

The following is the output:

```
"Ready to rock!"

started in  C:\Users\adama\Documents\stable-diffusion-ui\stable-diffusion-ui\stable-diffusion
←[32mINFO←[0m:     Started server process [←[36m16544←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://127.0.0.1:9000←[0m (Press CTRL+C to quit)
Traceback (most recent call last):
  File "C:\Users\adama\Documents\stable-diffusion-ui\stable-diffusion-ui\stable-diffusion\..\ui\server.py", line 56, in ping
    from sd_internal import runtime
  File "C:\Users\atomica\Documents\stable-diffusion-ui\stable-diffusion-ui\stable-diffusion\..\ui\sd_internal\runtime.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

←[32mINFO←[0m:     127.0.0.1:52859 - "←[1mGET /ping HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:52859 - "←[1mGET /ping HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:52859 - "←[1mGET /favicon.ico HTTP/1.1←[0m" ←[31m404 Not Found←[0m
←[32mINFO←[0m:     127.0.0.1:52859 - "←[1mGET /ping HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:52859 - "←[1mGET /ping HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:52859 - "←[1mGET /ping HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:52859 - "←[1mGET /ping HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:52859 - "←[1mGET /ping HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:52859 - "←[1mGET /ping HTTP/1.1←[0m" ←[32m200 OK←[0m
```

**Comment by cmdr2** [comment]
Hi @Atomica1 @yusefnapora - I've updated the v2 version with a new build. This checks for missing dependencies at the end and tries to fix them. Hopefully that should resolve the problem. You can download it from https://drive.google.com/file/d/1cEuOcb9OaldXcc2XzEMqEdvAr_w-KJ_p/view?usp=sharing and then double-click `Start Stable Diffusion UI.cmd` to install and run.

Please let me know if there are any problems after running it. Thanks!

PS: There's a new Discord server for support and development discussions: https://discord.com/invite/u9yhsFmEkB . Please join in for faster discussion and feedback on v2.

**Comment by Atomica1** [comment]
thank you for the reply ill let you know how it goes.
Much appreciated

-Adam

**Comment by Atomica1** [comment]
i was not able to connect initially,
reboot and am able to connect with server, got a green light however getting CUDA out of memory error.
reboot and trying with 256xx still getting the error
reboot and changed to 128xx..
i am trying to run with 6gb vram not likely to succeed but am hopeful it will be possible soon,
you mentioned adopting another method that is more optimized is that included in Version 2?

both folders seems to have merged after another reboot im getting the cv3 error agai.
is there a link for uninstall? :/ id like to clean this up and try again. 
I included my specs below and am hopeful that there will be a way to utulize integrated graphics soon..

CPU

	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

	Base speed:	2.59 GHz
	Sockets:	1
	Cores:	6
	Logical processors:	12
	Virtualization:	Enabled
	L1 cache:	384 KB
	L2 cache:	1.5 MB
	L3 cache:	12.0 MB

	Utilization	4%
	Speed	4.27 GHz
	Up time	0:00:12:32
	Processes	193
	Threads	2392
	Handles	78577

GPU 0

	Intel(R) UHD Graphics

	Driver version:	27.20.100.8190
	Driver date:	5/5/2020
	DirectX version:	12 (FL 12.1)
	Physical location:	PCI bus 0, device 2, function 0

	Utilization	0%
	Dedicated GPU memory	
	Shared GPU memory	0.0/15.9 GB
	GPU Memory	0.0/15.9 GB

GPU 1

	NVIDIA Quadro RTX 3000

	Driver version:	31.0.15.1659
	Driver date:	6/23/2022
	DirectX version:	12 (FL 12.1)
	Physical location:	PCI bus 1, device 0, function 0

	Utilization	2%
	Dedicated GPU memory	0.4/6.0 GB
	Shared GPU memory	0.0/15.9 GB
	GPU Memory	0.4/21.9 GB

**Comment by cmdr2** [comment]
Hi @Atomica1 Sorry about that. Just to make sure we start with a fresh installation, can you please try deleting the 'stable-diffusion-ui' folder on your computer? That's like uninstalling, because this project installs all the required files inside it.

And then please download and run https://drive.google.com/file/d/1toxjWESE0S2iUb-MWRf3WQ8S98Mr3Lex/view?usp=sharing (`Start Stable Diffusion UI.cmd`).

Once this starts, if you still get CUDA memory errors, you can try disabling `Turbo mode` from the Advanced options.

Please let me know if there are any problems. Thanks

**Comment by cmdr2** [comment]
Closing this, please try the latest installer, it checks and fixes a lot of issues. Feel free to re-open if this is still an issue, thanks.

**Comment by 19wolf** [comment]
I don't know if I can reopen this or if you want me to make a new issue, but I'm having this problem with the latest installer

**Comment by 19wolf** [comment]
```
>pip3 install opencv-python
Requirement already satisfied: opencv-python in c:\users\talos\appdata\local\programs\python\python310\lib\site-packages (4.6.0.66)
Requirement already satisfied: numpy>=1.14.5 in c:\users\talos\appdata\local\programs\python\python310\lib\site-packages (from opencv-python) (1.23.3)
```

**Comment by 19wolf** [comment]
I'm on Windows 10 if that matters

**Comment by 19wolf** [comment]
Here's the whole output:
```
>chdir C:\stable-diffusion-ui

C:\stable-diffusion-ui>"Start Stable Diffusion UI.cmd"

C:\stable-diffusion-ui>installer\Scripts\activate.bat
conda 4.14.0
git version 2.34.1.windows.1

(installer) C:\stable-diffusion-ui\installer\etc\conda\activate.d>cd C:\stable-diffusion-ui\installer\..\scripts

(installer) C:\stable-diffusion-ui\scripts>on_env_start.bat

"Stable Diffusion UI - v2"

"Stable Diffusion UI's git repository was already installed. Updating from main.."
HEAD is now at 1c5097b Hotfix for pywavelet version, attempt 1
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
sd-ui-files\ui\index.html
sd-ui-files\ui\modifiers.json
sd-ui-files\ui\server.py
sd-ui-files\ui\hotfix\9c24e6cd9f499d02c4f21a033736dabd365962dc80fe3aeb57a8f85ea45a20a3.26fead7ea4f0f843f6eb4055dfd25693f1a71f3c6871b184042d4b126244e142
sd-ui-files\ui\media\ding.mp3
sd-ui-files\ui\media\kofi.png
sd-ui-files\ui\sd_internal\ddim_callback.patch
sd-ui-files\ui\sd_internal\env_yaml.patch
sd-ui-files\ui\sd_internal\runtime.py
sd-ui-files\ui\sd_internal\__init__.py
10 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.

Hotfixed broken JSON file from OpenAI
"Stable Diffusion's git repository was already installed. Updating.."
HEAD is now at d154155 Merge pull request #122 from ryudrigo/main
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

HEAD is now at d154155 Merge pull request #122 from ryudrigo/main
"Packages necessary for Stable Diffusion were already installed"
"Packages necessary for GFPGAN (Face Correction) were already installed"
"Packages necessary for ESRGAN (Resolution Upscaling) were already installed"
"Packages necessary for Stable Diffusion UI were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded"
"Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded"

"Stable Diffusion is ready!"

PYTHONPATH=C:\stable-diffusion-ui\stable-diffusion;C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages
Python 3.8.5
started in  C:\stable-diffusion-ui\stable-diffusion
←[32mINFO←[0m:     Started server process [←[36m8100←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://0.0.0.0:9000←[0m (Press CTRL+C to quit)
←[32mINFO←[0m:     127.0.0.1:53600 - "←[1mGET / HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:53600 - "←[1mGET /media/kofi.png HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:53600 - "←[1mGET /modifiers.json HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:53600 - "←[1mGET /output_dir HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:53601 - "←[1mGET /favicon.ico HTTP/1.1←[0m" ←[31m404 Not Found←[0m
←[32mINFO←[0m:     127.0.0.1:53601 - "←[1mGET /app_config HTTP/1.1←[0m" ←[32m200 OK←[0m
Traceback (most recent call last):
  File "C:\stable-diffusion-ui\ui\server.py", line 74, in ping
    from sd_internal import runtime
  File "C:\stable-diffusion-ui\ui\sd_internal\runtime.py", line 19, in <module>
    from gfpgan import GFPGANer
  File "c:\stable-diffusion-ui\stable-diffusion\src\gfpgan\gfpgan\__init__.py", line 2, in <module>
    from .archs import *
  File "c:\stable-diffusion-ui\stable-diffusion\src\gfpgan\gfpgan\archs\__init__.py", line 2, in <module>
    from basicsr.utils import scandir
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\basicsr\__init__.py", line 3, in <module>
    from .archs import *
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\basicsr\archs\__init__.py", line 5, in <module>
    from basicsr.utils import get_root_logger, scandir
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\basicsr\utils\__init__.py", line 4, in <module>
    from .img_process_util import USMSharp, usm_sharp
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\basicsr\utils\img_process_util.py", line 1, in <module>
    import cv2
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: DLL load failed while importing cv2: The specified module could not be found.

INFO:     127.0.0.1:53600 - "GET /media/ding.mp3 HTTP/1.1" 200 OK
```
