### ISSUE TITLE
Fresh Install on Windows 11 can't run because of _fblas DLL error

### ISSUE THREAD

**Issue by marcelb** [cmdr2/stable-diffusion-ui#538]
**Describe the bug**
Installation works until the UI is started, then it fails with 
`ImportError: DLL load failed while importing _fblas: %1 is not a valid Win32 application.`

**To Reproduce**
1. Download Windows installer
2. Unpack on Windows 11 machine (it had git and python installed from a Visual Studio 2022 installation)
3. Move folder inside to C:\stable-diffusion-ui
4. Run "Start Stable Diffusion UI.cmd" and wait until the install completes and the UI is started.

**Expected behavior**
The UI should come up and run.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 2.4.13

**Additional context**

Whole run log (partially German, because its a Win11 in German):

```
C:\Program Files\Git\cmd\git.exe
git version 2.38.1.windows.1
C:\stable-diffusion-ui\installer_files\env\Library\bin\conda.bat
C:\stable-diffusion-ui\installer_files\env\Scripts\conda.exe
conda 22.9.0

"Stable Diffusion UI - v2"

"Stable Diffusion UI's git repository was already installed. Updating from main.."
HEAD is now at 1267621 Merge pull request #535 from cmdr2/beta
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
462 Datei(en) kopiert
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
        1 Datei(en) kopiert.
Ein Unterverzeichnis oder eine Datei mit dem Namen "tmp" existiert bereits.

Hotfixed broken JSON file from OpenAI
"Stable Diffusion's git repository was already installed. Updating.."
HEAD is now at 7f32368 Use a specific version of opencv-python
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

HEAD is now at 7f32368 Use a specific version of opencv-python
"Packages necessary for Stable Diffusion were already installed"
"Packages necessary for GFPGAN (Face Correction) were already installed"
"Packages necessary for ESRGAN (Resolution Upscaling) were already installed"
"Packages necessary for Stable Diffusion UI were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded. Using the HuggingFace 4 GB Model."
"Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded"
"Data files (weights) necessary for the default VAE (sd-vae-ft-mse-original) were already downloaded"

"Stable Diffusion is ready!"

PYTHONPATH=C:\stable-diffusion-ui\stable-diffusion;C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages
C:\stable-diffusion-ui\stable-diffusion\env\python.exe
C:\stable-diffusion-ui\installer_files\env\python.exe
C:\Users\User\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.8.5
started in  C:\stable-diffusion-ui\stable-diffusion
Traceback (most recent call last):
  File "C:\stable-diffusion-ui\stable-diffusion\env\Scripts\uvicorn-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\uvicorn\main.py", line 404, in main
    run(
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\stable-diffusion-ui\stable-diffusion\env\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\stable-diffusion-ui\stable-diffusion\env\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\uvicorn\config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
    raise exc from None
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\stable-diffusion-ui\stable-diffusion\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\stable-diffusion-ui\ui\server.py", line 53, in <module>
    from sd_internal import Request, Response, task_manager
  File "C:\stable-diffusion-ui\ui\sd_internal\task_manager.py", line 17, in <module>
    from sd_internal import Request, Response, runtime, device_manager
  File "C:\stable-diffusion-ui\ui\sd_internal\runtime.py", line 19, in <module>
    from pytorch_lightning import seed_everything
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\pytorch_lightning\__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\pytorch_lightning\metrics\__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\pytorch_lightning\metrics\classification\__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\pytorch_lightning\metrics\classification\accuracy.py", line 16, in <module>
    from torchmetrics import Accuracy as _Accuracy
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torchmetrics\__init__.py", line 44, in <module>
    from torchmetrics.image import FID, IS, KID, LPIPS, PSNR, SSIM  # noqa: E402
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torchmetrics\image\__init__.py", line 14, in <module>
    from torchmetrics.image.fid import FID  # noqa: F401
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torchmetrics\image\fid.py", line 27, in <module>
    from torch_fidelity.feature_extractor_inceptionv3 import FeatureExtractorInceptionV3
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch_fidelity\__init__.py", line 6, in <module>
    from torch_fidelity.metric_fid import KEY_METRIC_FID
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\torch_fidelity\metric_fid.py", line 6, in <module>
    import scipy.linalg
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\scipy\linalg\__init__.py", line 197, in <module>
    from ._misc import *
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\scipy\linalg\_misc.py", line 3, in <module>
    from .blas import get_blas_funcs
  File "C:\stable-diffusion-ui\stable-diffusion\env\Lib\site-packages\scipy\linalg\blas.py", line 213, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed while importing _fblas: %1 is not a valid Win32 application.
Drücken Sie eine beliebige Taste . . .
```

**Comment by jcobreros** [comment]
I have been fighting this error since last night. Today I restarted my computer, did a fresh install of this repo and it's working (well, installation worked. Now I'm getting black images, but that's a different problem)

**Comment by marcelb** [comment]
Interesting, did you download the release or did you get the lastest main and build it yourself?

**Comment by jcobreros** [comment]
I downloaded the release

**Comment by JeLuF** [comment]
Which GPU are you using? The software should activate full precision for GPUs requiring it automatically, so this would mean that your GPU is missing on the list.

**Comment by jcobreros** [comment]
It's an RTX3070 Mobile (8GB)

**Comment by marcelb** [comment]
This initial bug is solved. I recently updated and it's gone. It now starts on the same machine without issues.

**Comment by marcelb** [comment]
Not sure what exactly fixed it, but multiple repos updated and it's working alright.
