### ISSUE TITLE
ModuleNotFoundError: No module named 'ldm'

### ISSUE THREAD

**Issue by i2chris** [cmdr2/stable-diffusion-ui#57]
I installed stable-diffussion-ui (v2) yesterday and it worked first time, no problems.  I generated loads of images.

I've just run it again today and I get this exception which stops images from being generated:

```
conda 4.14.0
git version 2.34.1.windows.1

(installer) C:\stable-diffusion-ui\installer\etc\conda\activate.d>cd C:\stable-diffusion-ui\installer\..\scripts

(installer) C:\stable-diffusion-ui\scripts>on_env_start.bat

"Stable Diffusion UI"

"Stable Diffusion UI's git repository was already installed. Updating.."
HEAD is now at 90c4361 Update README.md
Already up to date.
sd-ui-files\ui\index.html
sd-ui-files\ui\modifiers.json
sd-ui-files\ui\server.py
sd-ui-files\ui\media\ding.mp3
sd-ui-files\ui\sd_internal\runtime.py
sd-ui-files\ui\sd_internal\__init__.py
6 File(s) copied
sd-ui-files\scripts\on_env_start.bat
sd-ui-files\scripts\on_env_start.sh
sd-ui-files\scripts\on_sd_start.bat
sd-ui-files\scripts\on_sd_start.sh
sd-ui-files\scripts\post_activate.bat
sd-ui-files\scripts\post_activate.sh
sd-ui-files\scripts\Start Stable Diffusion UI.cmd
sd-ui-files\scripts\start.sh
sd-ui-files\scripts\win_enable_long_filepaths.ps1
9 File(s) copied
"Stable Diffusion's git repository was already installed. Updating.."
HEAD is now at 1857272 Create FUNDING.yml
Already up to date.
"Packages necessary for Stable Diffusion were already installed"
"Packages necessary for Stable Diffusion UI were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded"

"Stable Diffusion is ready!"

started in  C:\stable-diffusion-ui\stable-diffusion
←[32mINFO←[0m:     Started server process [←[36m3928←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://[0.0.0.0:9000](http://0.0.0.0:9000/)←[0m (Press CTRL+C to quit)
←[32mINFO←[0m:     [127.0.0.1:64582](http://127.0.0.1:64582/) - "←[1mGET / HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     [127.0.0.1:64582](http://127.0.0.1:64582/) - "←[1mGET /output_dir HTTP/1.1←[0m" ←[32m200 OK←[0m
Traceback (most recent call last):
  File "C:\stable-diffusion-ui\stable-diffusion\..\ui\server.py", line 63, in ping
    from sd_internal import runtime
  File "C:\stable-diffusion-ui\stable-diffusion\..\ui\sd_internal\runtime.py", line 14, in <module>
    from ldm.util import instantiate_from_config
ModuleNotFoundError: No module named 'ldm'
```

The web UI works fine, just not the image generation.

**Comment by cmdr2** [comment]
Hi @i2chris Sorry about that. Can you please try running the server one more time? Is it still happening? Thanks

**Comment by i2chris** [comment]
I just ran it again and everything is good now. 

This could be my own fault.  I moved the folder from c:\stable-diffusion-ui to d:\stable-diffussion-ui (an SSD), hoping to improve performance slightly, but it just gave that error message.  Now I've moved it back it works fine.

**Comment by cmdr2** [comment]
Hi @i2chris , thanks. The underlying package manager (conda) doesn't like being moved after installation.

I'd suggest re-installing on d: and copying the `stable-diffusion-ui/stable-diffusion/sd-v1-4.ckpt` (4 GB) file to avoid re-downloading it, as soon as it is done with the "Downloading packages for Stable Diffusion" step.

The SSD will definitely help improve the app run faster, since it needs to load the 4GB model file when it starts (or changes between text-only and initial-image modes).
