### ISSUE TITLE
Unable to start Stable Diffusion after most recent update

### ISSUE THREAD

**Issue by zenntenn** [cmdr2/stable-diffusion-ui#617]
I was fine running Stable Diffusion yesterday, but today when I try to start it it says "Stable Diffusion has stopped" in the top right corner of the UI.

I'm running Arch Linux, using an Intel processor and no compatible GPU.

Here's the command line errors I'm getting. The last line just keeps repeating the longer I leave it.

```
[zenten@bahamut stable-diffusion-ui]$ ./start.sh 
scripts/bootstrap.sh: line 9: ./scripts/functions.sh: No such file or directory
/home/zenten/stable-diffusion-ui/installer/bin/git
git version 2.34.1
/home/zenten/stable-diffusion-ui/installer/bin/conda
conda 4.14.0
scripts/on_env_start.sh: line 3: ./scripts/functions.sh: No such file or directory


Stable Diffusion UI

Stable Diffusion UI's git repository was already installed. Updating from main..
HEAD is now at 9571b8a Merge pull request #614 from cmdr2/beta
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
./scripts/on_sd_start.sh: line 3: ./scripts/functions.sh: No such file or directory

Hotfixed broken JSON file from OpenAI
Stable Diffusion's git repository was already installed. Updating..
HEAD is now at 7f32368 Use a specific version of opencv-python
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

HEAD is now at 7f32368 Use a specific version of opencv-python
Packages necessary for Stable Diffusion were already installed
Packages necessary for GFPGAN (Face Correction) were already installed
Packages necessary for ESRGAN (Resolution Upscaling) were already installed
Packages necessary for Stable Diffusion UI were already installed
Picklescan is already installed.
SafeTensors is already installed.
Data files (weights) necessary for Stable Diffusion were already downloaded
Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded
Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded
Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded
Data files (weights) necessary for the default VAE (sd-vae-ft-mse-original) were already downloaded


Stable Diffusion is ready!

PYTHONPATH=/home/zenten/stable-diffusion-ui/stable-diffusion:/home/zenten/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages
/home/zenten/stable-diffusion-ui/stable-diffusion/env/bin/python
Python 3.8.5
started in  /home/zenten/stable-diffusion-ui/stable-diffusion
[32101:32101:1206/104915.992880:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104916.002093:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104916.011346:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104916.027031:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104916.044401:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104916.611733:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
Scan /home/zenten/stable-diffusion-ui/models/stable-diffusion/sd-v1-5-inpainting.ckpt: 1 scanned, 0 issue, 0 infected.
Scan /home/zenten/stable-diffusion-ui/models/stable-diffusion/SF_EB_1.1_ema_vae.ckpt: 1 scanned, 0 issue, 0 infected.
[32101:32101:1206/104917.195375:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
Scan /home/zenten/stable-diffusion-ui/models/stable-diffusion/SF_EB_1.1_SD50_ema_vae.ckpt: 1 scanned, 0 issue, 0 infected.
[32101:32101:1206/104917.325730:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
Scan /home/zenten/stable-diffusion-ui/models/stable-diffusion/openjourneyAkaMid..._v1.ckpt: 1 scanned, 0 issue, 0 infected.
Scan /home/zenten/stable-diffusion-ui/models/stable-diffusion/v1-5-pruned-emaonly.ckpt: 1 scanned, 0 issue, 0 infected.
Scan /home/zenten/stable-diffusion-ui/models/stable-diffusion/persona5Shigenori..._v1.ckpt: 1 scanned, 0 issue, 0 infected.
Scan /home/zenten/stable-diffusion-ui/models/vae/vae-ft-mse-840000-ema-pruned.ckpt: 1 scanned, 0 issue, 0 infected.
requesting for render_devices auto
WARNING: Could not find a compatible GPU. Using the CPU, but this will be very slow!
devices_to_start {'cpu'}
devices_to_stop set()
Start new Rendering Thread on device cpu
Render device CPU available as Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
loading /home/zenten/stable-diffusion-ui/models/stable-diffusion/sd-v1-5-inpainting.ckpt to device cpu using precision full
Loading model from /home/zenten/stable-diffusion-ui/models/stable-diffusion/sd-v1-5-inpainting.ckpt
[32101:32101:1206/104917.913965:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104918.224697:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
active devices {'cpu': {'name': 'Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz'}}
[32101:32101:1206/104918.827486:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
Global Step: 440000
UNet: Running in eps-prediction mode
[32101:32101:1206/104919.213435:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104919.811375:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104920.052465:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104920.061398:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104920.077714:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104920.093869:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104920.110761:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104920.127585:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104920.738909:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104920.773252:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
INFO:     Started server process [35978]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:9000 (Press CTRL+C to quit)
Opening in existing browser session.
INFO:     127.0.0.1:41608 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:41608 - "GET /css/fonts.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:41616 - "GET /css/themes.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:41622 - "GET /css/main.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:41630 - "GET /css/auto-save.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:41650 - "GET /css/fontawesome-all.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:41630 - "GET /css/jquery-confirm.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:41608 - "GET /js/jquery-confirm.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:41622 - "GET /js/jquery-3.6.1.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:41642 - "GET /js/marked.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:41622 - "GET /js/utils.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:41642 - "GET /js/parameters.js HTTP/1.1" 200 OK
[32101:32101:1206/104922.077170:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
INFO:     127.0.0.1:41642 - "GET /js/plugins.js HTTP/1.1" 200 OK
[32101:32101:1206/104922.098369:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
INFO:     127.0.0.1:41622 - "GET /js/auto-save.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:41608 - "GET /js/dnd.js HTTP/1.1" 200 OK
[32101:32101:1206/104922.114040:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
INFO:     127.0.0.1:41642 - "GET /js/main.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:41630 - "GET /js/themes.js HTTP/1.1" 200 OK
[32101:32101:1206/104922.126961:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.144388:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
INFO:     127.0.0.1:41650 - "GET /fonts/work-sans-v18-latin-700.woff2 HTTP/1.1" 200 OK
INFO:     127.0.0.1:41642 - "GET /fonts/work-sans-v18-latin-regular.woff2 HTTP/1.1" 200 OK
INFO:     127.0.0.1:41630 - "GET /fonts/fa-solid-900.woff2 HTTP/1.1" 200 OK
INFO:     127.0.0.1:41608 - "GET /fonts/fa-regular-400.woff2 HTTP/1.1" 200 OK
[32101:32101:1206/104922.161193:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.187624:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.206492:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.221537:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.238434:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
INFO:     127.0.0.1:41630 - "GET /get/models HTTP/1.1" 200 OK
[32101:32101:1206/104922.255404:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.270852:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.296387:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.297179:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.312612:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
INFO:     127.0.0.1:41630 - "GET /get/app_config HTTP/1.1" 200 OK
[32101:32101:1206/104922.333647:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
INFO:     127.0.0.1:41658 - "GET /manifest.webmanifest HTTP/1.1" 200 OK
[32101:32101:1206/104922.344657:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
INFO:     127.0.0.1:41630 - "GET /get/ui_plugins HTTP/1.1" 200 OK
INFO:     127.0.0.1:41650 - "GET /Modifiers-wheel.plugin.js?t=1670341762352 HTTP/1.1" 200 OK
INFO:     127.0.0.1:41642 - "GET /modifiers-toggle.plugin.js?t=1670341762352 HTTP/1.1" 200 OK
INFO:     127.0.0.1:41630 - "GET /custom-modifiers.plugin.js?t=1670341762351 HTTP/1.1" 200 OK
INFO:     127.0.0.1:41608 - "GET /Modifiers-dnd.plugin.js?t=1670341762352 HTTP/1.1" 200 OK
INFO:     127.0.0.1:41616 - "GET /Autoscroll.plugin.js?t=1670341762352 HTTP/1.1" 200 OK
INFO:     127.0.0.1:41622 - "GET /release-notes.plugin.js?t=1670341762353 HTTP/1.1" 200 OK
[32101:32101:1206/104922.363562:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
INFO:     127.0.0.1:41650 - "GET /get/modifiers HTTP/1.1" 200 OK
[32101:32101:1206/104922.383240:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
INFO:     127.0.0.1:41650 - "GET /js/marked.min.js HTTP/1.1" 200 OK
[32101:32101:1206/104922.394971:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.415501:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.438611:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.449197:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.474171:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.490587:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.506635:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.520110:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.536062:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
INFO:     127.0.0.1:41642 - "GET /get/app_config HTTP/1.1" 200 OK
[32101:32101:1206/104922.552440:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
INFO:     127.0.0.1:41630 - "GET /fonts/work-sans-v18-latin-800.woff2 HTTP/1.1" 200 OK
[32101:32101:1206/104922.569825:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.586780:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.602430:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
INFO:     127.0.0.1:41608 - "GET /get/system_info HTTP/1.1" 200 OK
[32101:32101:1206/104922.837148:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104922.847575:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
INFO:     127.0.0.1:41622 - "GET /ding.mp3 HTTP/1.1" 200 OK
[32101:32101:1206/104923.188195:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104923.340578:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104923.844674:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104924.349563:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104924.855808:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
Traceback (most recent call last):
  File "/home/zenten/stable-diffusion-ui/ui/sd_internal/task_manager.py", line 199, in preload_model
    runtime.load_model_ckpt()
  File "/home/zenten/stable-diffusion-ui/ui/sd_internal/runtime.py", line 121, in load_model_ckpt
    load_model_ckpt_sd1()
  File "/home/zenten/stable-diffusion-ui/ui/sd_internal/runtime.py", line 145, in load_model_ckpt_sd1
    _, _ = model.load_state_dict(sd, strict=False)
  File "/home/zenten/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet:
	size mismatch for model1.diffusion_model.input_blocks.0.0.weight: copying a param with shape torch.Size([320, 9, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).

[32101:32101:1206/104925.358249:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104925.862296:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104926.036727:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104926.366265:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104926.542373:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104926.780394:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104926.815558:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
[32101:32101:1206/104931.995346:ERROR:vulkan_swap_chain.cc(408)] Swapchain is suboptimal.
```

**Comment by zenntenn** [comment]
Looks like it was just from a custom model I was using. Weird that it worked fine yesterday though.
