### ISSUE TITLE
MemoryError on 1050ti

### ISSUE THREAD

**Issue by Fialki** [cmdr2/stable-diffusion-ui#807]
Hi.
Please help I can't start stable diffusion, getting a MemoryError.

Configuration PC
Gigabyte 990fxa-ud3 r3
AMD FX(tm)-6300 Six-Core Processor  3.50 GHz
RAM  8GiB DDR3
Nvidia GTX 1050ti 4GiB

Console log:
F:\StableDiffusion\installer_files\env\Library\bin\git.exe
git version 2.39.1.windows.1
F:\StableDiffusion\installer_files\env\Library\bin\conda.bat
F:\StableDiffusion\installer_files\env\Scripts\conda.exe
conda 22.11.1

"Stable Diffusion UI - v2"

"Stable Diffusion UI's git repository was already installed. Updating from main.."
HEAD is now at 1da4b3d Not all browsers return the PerformanceEntry object on performance.measure(). Fix credit @JeLuf
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
482 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file tmp already exists.

Hotfixed broken JSON file from OpenAI
"Stable Diffusion's git repository was already installed. Updating.."
HEAD is now at 7f32368 Use a specific version of opencv-python
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

HEAD is now at 7f32368 Use a specific version of opencv-python
"Packages necessary for Stable Diffusion were already installed"
"Packages necessary for GFPGAN (Face Correction) were already installed"
"Packages necessary for ESRGAN (Resolution Upscaling) were already installed"
"Packages necessary for Stable Diffusion UI were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded. Using the HuggingFace 4 GB Model."
"Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded"
"Data files (weights) necessary for the default VAE (sd-vae-ft-mse-original) were already downloaded"

"Stable Diffusion is ready!"

PYTHONPATH=F:\StableDiffusion\stable-diffusion;F:\StableDiffusion\stable-diffusion\env\Lib\site-packages
F:\StableDiffusion\stable-diffusion\env\python.exe
F:\StableDiffusion\installer_files\env\python.exe
Python 3.8.5
started in  F:\StableDiffusion\stable-diffusion
Scan F:\StableDiffusion\models\vae\vae-ft-mse-840000-ema-pruned.ckpt: 1 scanned, 0 issue, 0 infected.
requesting for render_devices auto
devices_to_start {'cuda:0'}
devices_to_stop set()
Start new Rendering Thread on device cuda:0
Setting cuda:0 as active
loading F:\StableDiffusion\stable-diffusion\sd-v1-4.ckpt to device cuda:0 using precision autocast
Loading model from F:\StableDiffusion\stable-diffusion\sd-v1-4.ckpt
active devices {'cuda:0': {'name': 'NVIDIA GeForce GTX 1050 Ti', 'mem_free': 3.53417298, 'mem_total': 4.294705152}}
INFO:     Started server process [7872]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
INFO:     127.0.0.1:51744 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:51744 - "GET /css/fonts.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:51745 - "GET /css/themes.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:51746 - "GET /css/main.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:51745 - "GET /css/auto-save.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:51745 - "GET /css/fontawesome-all.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:51744 - "GET /css/jquery-confirm.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:51745 - "GET /js/jquery-3.6.1.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51746 - "GET /js/jquery-confirm.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51744 - "GET /js/marked.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51745 - "GET /js/utils.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51744 - "GET /js/engine.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51745 - "GET /js/parameters.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51746 - "GET /js/plugins.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51746 - "GET /js/auto-save.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51745 - "GET /js/main.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51744 - "GET /js/themes.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51746 - "GET /js/dnd.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:51750 - "GET /fonts/fa-regular-400.woff2 HTTP/1.1" 200 OK
INFO:     127.0.0.1:51744 - "GET /fonts/work-sans-v18-latin-700.woff2 HTTP/1.1" 200 OK
INFO:     127.0.0.1:51745 - "GET /fonts/work-sans-v18-latin-regular.woff2 HTTP/1.1" 200 OK
INFO:     127.0.0.1:51746 - "GET /fonts/fa-solid-900.woff2 HTTP/1.1" 200 OK
INFO:     127.0.0.1:51746 - "GET /get/models HTTP/1.1" 200 OK
INFO:     127.0.0.1:51746 - "GET /get/app_config HTTP/1.1" 200 OK
INFO:     127.0.0.1:51746 - "GET /get/ui_plugins HTTP/1.1" 200 OK
INFO:     127.0.0.1:51750 - "GET /modifiers-toggle.plugin.js?t=1675027366337 HTTP/1.1" 200 OK
INFO:     127.0.0.1:51745 - "GET /custom-modifiers.plugin.js?t=1675027366336 HTTP/1.1" 200 OK
INFO:     127.0.0.1:51746 - "GET /Autoscroll.plugin.js?t=1675027366335 HTTP/1.1" 200 OK
INFO:     127.0.0.1:51751 - "GET /Modifiers-wheel.plugin.js?t=1675027366339 HTTP/1.1" 200 OK
INFO:     127.0.0.1:51744 - "GET /Modifiers-dnd.plugin.js?t=1675027366336 HTTP/1.1" 200 OK
INFO:     127.0.0.1:51744 - "GET /release-notes.plugin.js?t=1675027366342 HTTP/1.1" 200 OK
INFO:     127.0.0.1:51746 - "GET /selftest.plugin.js?t=1675027366343 HTTP/1.1" 200 OK
INFO:     127.0.0.1:51744 - "GET /js/marked.min.js?t=1675027366429 HTTP/1.1" 200 OK
INFO:     127.0.0.1:51750 - "GET /get/modifiers HTTP/1.1" 200 OK
INFO:     127.0.0.1:51756 - "GET /manifest.webmanifest HTTP/1.1" 200 OK
INFO:     127.0.0.1:51745 - "GET /get/system_info HTTP/1.1" 200 OK
INFO:     127.0.0.1:51751 - "GET /get/app_config HTTP/1.1" 200 OK
INFO:     127.0.0.1:51745 - "GET /ding.mp3 HTTP/1.1" 200 OK
Global Step: 470000
UNet: Running in eps-prediction mode
CondStage: Running in eps-prediction mode
Traceback (most recent call last):
  File "F:\StableDiffusion\stable-diffusion\env\Lib\site-packages\transformers\modeling_utils.py", line 392, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "F:\StableDiffusion\stable-diffusion\env\Lib\site-packages\torch\serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "F:\StableDiffusion\stable-diffusion\env\Lib\site-packages\torch\serialization.py", line 1046, in _load
    result = unpickler.load()
  File "F:\StableDiffusion\stable-diffusion\env\Lib\site-packages\torch\serialization.py", line 1016, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "F:\StableDiffusion\stable-diffusion\env\Lib\site-packages\torch\serialization.py", line 997, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch._UntypedStorage).storage()._untyped()
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 9437184 bytes.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\StableDiffusion\ui\sd_internal\task_manager.py", line 255, in preload_model
    runtime.load_model_ckpt()
  File "F:\StableDiffusion\ui\sd_internal\runtime.py", line 128, in load_model_ckpt
    load_model_ckpt_sd1()
  File "F:\StableDiffusion\ui\sd_internal\runtime.py", line 164, in load_model_ckpt_sd1
    modelCS = instantiate_from_config(config.modelCondStage)
  File "F:\StableDiffusion\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "F:\StableDiffusion\stable-diffusion\optimizedSD\ddpm.py", line 262, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "F:\StableDiffusion\stable-diffusion\optimizedSD\ddpm.py", line 282, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "F:\StableDiffusion\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "F:\StableDiffusion\stable-diffusion\ldm\modules\encoders\modules.py", line 142, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File "F:\StableDiffusion\stable-diffusion\env\Lib\site-packages\transformers\modeling_utils.py", line 1978, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "F:\StableDiffusion\stable-diffusion\env\Lib\site-packages\transformers\modeling_utils.py", line 396, in load_state_dict
    if f.read().startswith("version"):
MemoryError

 - OS: Windows 10 Pro 22H2
 - Browser: Google Chrome
 - Version: 109.0.5414.120

**Comment by Fialki** [comment]
The problem is solved.

What is the problem:
lack of RAM and incorrect operation SWAP on SSD

Solution:
Transfer SWAP from SSD to HDD and set a fixed minimum size 10 GiB
