### ISSUE TITLE
Beta channel, on linux, crash on startup

### ISSUE THREAD

**Issue by Anyvie** [cmdr2/stable-diffusion-ui#825]
**Describe the bug**
Beta channel, on linux, crash on startup, showing :
`ImportError: libGL.so.1: cannot open shared object file: No such file or directory`

**To Reproduce**
1. Download the linux installation file, and launch start.sh
2. On web UI settings, check beta channel and save
3. Ctrl+C the app, and start it again
4. On next launch : "ImportError: libGL.so.1: cannot open shared object file: No such file or directory"

**Log**
```
$ ./start.sh 2>&1
/usr/bin/git
git version 2.30.2
/home/debian/stable-diffusion-ui/installer_files/env/bin/conda
conda 22.11.1


Stable Diffusion UI

Stable Diffusion UI's git repository was already installed. Updating from beta..
HEAD is now at d48e655 Merge branch 'beta' of github.com:cmdr2/stable-diffusion-ui into beta
Already on 'beta'
Your branch is up to date with 'origin/beta'.
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.

Hotfixed broken JSON file from OpenAI
torch and torchvision have already been installed.
sdkit is already installed.
sdkit version: 1.0.32
stable-diffusion version: 2.1.1
rich has already been installed.
Packages necessary for Stable Diffusion UI were already installed
Data files (weights) necessary for Stable Diffusion were already downloaded
Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded
Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded
Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded
Data files (weights) necessary for the default VAE (sd-vae-ft-mse-original) were already downloaded


Stable Diffusion is ready!

PYTHONPATH=/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages
/home/debian/stable-diffusion-ui/stable-diffusion/env/bin/python
Python 3.8.5
Traceback (most recent call last):
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/bin/uvicorn", line 11, in <module>
    sys.exit(main())
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/uvicorn/main.py", line 404, in main
    run(
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/debian/stable-diffusion-ui/ui/main.py", line 1, in <module>
    from easydiffusion import model_manager, app, server
  File "/home/debian/stable-diffusion-ui/ui/easydiffusion/model_manager.py", line 3, in <module>
    from easydiffusion import app, device_manager
  File "/home/debian/stable-diffusion-ui/ui/easydiffusion/app.py", line 9, in <module>
    from sdkit.utils import log as sdkit_log # hack, so we can overwrite the log config
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/sdkit/utils/__init__.py", line 24, in <module>
    from .image_utils import (
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/sdkit/utils/image_utils.py", line 2, in <module>
    import cv2
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/debian/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
Press any key to continue
Press any key to continue
```

**Desktop (please complete the following information):**
 - OS: Debian 11.6

**Comment by Anyvie** [comment]
I'll try that ASAP. 

And I know this is a Beta channel, so can be risky.
I opened the issue anyway because of this :

```
Easy for new users, powerful features for advanced users
Features:
User experience
    Hassle-free installation: Does not require technical knowledge, does not require pre-installed software. Just download and run!
```

**Comment by JeLuF** [comment]
> I'll try that ASAP.
> 
> And I know this is a Beta channel, so can be risky. I opened the issue anyway because of this :
> 
> ```
> Easy for new users, powerful features for advanced users
> Features:
> User experience
>     Hassle-free installation: Does not require technical knowledge, does not require pre-installed software. Just download and run!
> ```

Do you use a desktop (like Gnome, KDE, ...) on your Linux installation, or is it a headless setup?

**Comment by Anyvie** [comment]
headless, on a remote server via SSH

**Comment by Anyvie** [comment]
> Your system doesn't have libGL1 installed. On Ubuntu you can install it via:
> `apt install libgl1-mesa-glx`
> I didn't check whether the Debian package has the same name.

I can confirm that it does solve the issue.
